### ISSUE TITLE
What is the new argument to StmAdd?

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#10]
Hey Emilio,

What does the new integer in StmAdd do? 

```
(test (Control (StmAdd 0 2 "Goal forall n, n + 0 = n.")))
                       ^ this one
  (Answer test Ack)
  (Answer test Completed)
```

Also, does StmAdd no return the added state any more? It used to show the state id for the sentence that was just added. It still seems to do that if I pass it a number greater than 0 though :)

Thanks!

**Comment by ejgallego** [comment]
Hi Clément, 

sorry for so many changes and thanks for your patience.

The new number indicates a maximum of statements to be parsed. Since d100e0ee , StmAdd will try to parse whole documents (experimental feature). Thus if you pass 0, 0 sentences will be parsed :)

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by cpitclaudel** [comment]
Btw, I think it's really cool that many changes are happening; I really don't want my little experiments to slow down developments :)

**Comment by ejgallego** [comment]
Cool, thanks, indeed your comments are mostly what motivates the changes! I'll try to put a warning on the second line of the commit msg each time I break the API thou.
