### ISSUE TITLE
SerAPI vs TCoq

### ISSUE THREAD

**Issue by brando90** [ejgallego/coq-serapi#109]
Hopefully Questions are also welcome here. But I was wondering, what is the advantages/disadvantages and difference between using SerAPI vs TCoq?

https://github.com/ml4tp/tcoq

**Comment by palmskog** [comment]
TCoq is a fork of Coq (8.6.1), while SerAPI is a library that hooks into Coq's internals (8.8 or 8.9). TCoq looks like it will require substantial effort to port to a recent version of Coq, while SerAPI uses metaprogramming (PPX) to avoid quite a lot of maintenance effort. From cursory inspection, it looks like the key TCoq functionality could have been written on top of SerAPI.

**Comment by brando90** [comment]
@palmskog 

are those comments true/valid?

```
* We may have been able to use Coq-SerAPI, but I don't think it handles
 *   1. Outputting of shared representation
 *   2. Breaking up of semicolons
 * 
 * Wishlist: dump out the kernel-level AST in sexpr format.
 *)
```

**Comment by brando90** [comment]
To add to what I am truly wondering is, given a Coq script, TCoq's/Gamepads interesting features is that it can break down compound tactics (that manipulate the proof state [context+goal] in multiple steps) into its atomic tactics. I am wondering, can this be achieved with SerAPI? (i.e. the additional data is dumped out to get the full and atomic proof tree).

**Comment by palmskog** [comment]
Basically, SerAPI has sexps for all relevant Coq datastructures, which includes tactics. For example, the tactic sequence `destruct in_dec; intuition; subst; simpl; auto.` becomes (simplified):
```
(TacThen(TacThen(TacThen(TacThen(TacAtom((TacInductionDestruct false false((((()(ElimOnConstr(((v(CApp(()((v(CRef((v(Ser_Qualid(DirPath())(Id in_dec))))()))))((((v(CHole()IntroAnonymous())))())))))NoBindings)))(()())()))()))))(TacAlias(((Kername(MPfile(DirPath((Id Tauto)(Id Init)(Id Coq))))(DirPath())(Id intuition_3AD8AF16))()))))(TacAlias(((Kername(MPfile(DirPath((Id Notations)(Id Init)(Id Coq))))(DirPath())(Id subst_4C69D530))()))))(TacAtom((TacReduce(Simpl((rBeta true)(rMatch true)(rFix true)(rCofix true)(rZeta true)(rDelta true)(rConst()))())((onhyps(()))(concl_occs AllOccurrences))))))(TacAlias(("[LOC]")((Kername(MPfile(DirPath((Id Notations)(Id Init)(Id Coq))))(DirPath())(Id auto_#_#_#_4C69D5EB))((TacGeneric(GenArg raw(OptArg(ExtraArg int_or_var))()))(TacGeneric(GenArg raw(ExtraArg auto_using)()))(TacGeneric(GenArg raw(ExtraArg hintbases)(()))))))))
```

**Comment by ejgallego** [comment]
Hi folks, thanks a lot for the comments, indeed this should be added to the FAQ. Let me add my 2 cents here:

- In principle, SerAPI was designed to allow the kind of work `tcoq` is doing. But as you well know the devil is in the details so it could be well the case that the current design of SerAPI has some limitations that would make life hard.
- I am positive that most of TCoq printers are equivalent to the ones you get in SerAPI, maybe with some post-processing added.
- Indeed @palmskog outlined the main difference both approaches have wrt Coq integration. TCoq is a fork of Coq whose changes would have a hard time being upstreamed; SerAPI does however try hard to become a project that could be distributed along the main Coq distribution. SerAPI is still not officially "part of Coq", but it will be so some day very likely.



> I don't know what they exactly mean by shared representation

Ditto here. In general, I'd say that meaningful feature extraction may require more than the AST of a program [for example some dynamic information].

> TCoq's/Gamepads interesting features is that it can break down compound tactics (that manipulate the proof state [context+goal] in multiple steps) into its atomic tactics. I am wondering, can this be achieved with SerAPI?

Depending on your exact definition of "breaking down" compound tactics the answer would be yes or a bit more of work needed [if for example you'd like to resolve certain aliases]

Note that when TCoq was written SerAPI likely had poor or none support for LTAC serialization [this happened thanks to @palmskog quite recently], thus indeed the TCoq authors may have been discouraged by that.

**Comment by ejgallego** [comment]
Another important difference indeed could be in support level. SerAPI should hopefully be supported at least for the short term [hopefully more of course, and ideally for as long as Coq is supported]
