### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by brando90** [ejgallego/coq-serapi#110]
I was trying to find the documentation of how to use SerAPI (something in the style of read the doc) but I wasn't able to find it. I obviously saw the comment in the read me (https://github.com/ejgallego/coq-serapi/blame/v8.9/README.md#L43):

> Quick Overview and Documentation:
> SerAPI can be installed as the OPAM package coq-serapi. See build instructions for manual installation. The experimental in-browser version is also online.
> 
> The principal entry point in SerAPI is the sertop REPL, a basic toplevel that reads and executes commands (S-Expressions) from stdin to stdout in both machine or human-friendly format. See sertop --help for an overview of the main options. Ctrl-C will interrupt a busy Coq process in the same way coqtop does.
> 
> We recommend rlwrap or the emacs mode for direct interaction.

however, there didn't seem to be a link to a docs page. Did I perhaps miss something obvious or something else?

Thanks! :)

**Comment by ejgallego** [comment]
Indeed @brando90 documentation is mostly missing, sorry; however I have a branch that adds quite a lot of documentation to SerAPI, and IMHO it should be ready soon.

**Comment by palmskog** [comment]
As a memento, I think there should be details on `sercomp` and `compser` in the documentation, possibly even showing how they apply to a small Coq development. I think they should be framed as "example clients" of serlib+Coq to emulate.

**Comment by ejgallego** [comment]
While we get the documentation branch ready, @brando90 the main reference is the `.mli` file itself.

https://github.com/ejgallego/coq-serapi/blob/v8.9/serapi/serapi_protocol.mli

It is fairly easy to derive the protocol from the type declarations in that file.
