### ISSUE TITLE
[sercomp] Should we merge compser / sercomp ?

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#111]
As of today, `compser` / `sercomp` share the exact same codebase except for the input format.

The existence of two binaries is mostly an historical issue.

Should we indeed merge them and add an `--input_mode` option?

cc: @palmskog

**Comment by palmskog** [comment]
I'm OK with this, but could we keep `compser`/`sercomp` separate in some historical branch? Or can we at least make a tag of `v8.9+more_ssr_fix`?

**Comment by ejgallego** [comment]
Sure, this would be for 8.10, and we could indeed generate both binaries and set the option based on the name.

But now that I realize indeed I've changed already the `v8.9+more_ssr_fix` branch to point to v8.10, I forgot it would have had users! Ups. Let me try to fix it.

**Comment by ejgallego** [comment]
Ok old tree is in https://github.com/ejgallego/coq-serapi/tree/v8.9%2Bssreflect_serialization which should remain stable.

If that's a problem I'll revert the old branch and open a new PR then.

**Comment by ejgallego** [comment]
Yeah let me do that better.

**Comment by ejgallego** [comment]
Reifying the milestone, this is indeed a large change for a minor version but I guess we can live with it.
