### ISSUE TITLE
Add feedback filters [Was `.glob` support?]

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#12]
Feedback has the capability to send Coq `.glob` information messages. However, I am not sure this is really useful, and it is very very verbose.

What do @cpitclaudel @Ptival think ?

It is enabled in the current build, but I dunno what to do.

**edit:** We will implement a feedback filter in SerAPI, so clients can opt-out to receive certain kinds of feedback.

**Comment by cpitclaudel** [comment]
I'm not very interested in it. Ideally, I'd like to be able to query Coq for information about identifiers, but I don't need to get all that information through feedback messages.

**Comment by Ptival** [comment]
I'll follow Clément's advice on this, I have never looked at these `.glob` files.

I would love any type of dependency tracking, but I'd be happy to use the solutions already used by company-coq.

**Comment by ejgallego** [comment]
Cool thanks! I'm implementing a feedback filtering option, will make the `.glob` stuff disabled by default.

**Comment by ejgallego** [comment]
After some more experience with the protocol, having a feedback filter is not so important; verbosity levels would be better controlled upstream.
