### ISSUE TITLE
[serapi] `Completed` answer is not consistent w.r.t. to `CoqExn`

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#124]
In some cases, a command will produce an exception but still return a completed; while in others, it won't return completed.

I thing having both behaviors is a bug; we should pick one.

cc: @brando90

**Comment by ejgallego** [comment]
I kind prefer to always return completed as errors / exceptions are really diagnostics, and several of them can in general happen, we can have some form of error recovery for example.

**Comment by palmskog** [comment]
From a (distributed) protocol point of view, I think it makes sense to guarantee that a `Completed` answer is always sent eventually. Before the `Completed`, there could arguably be any number of diagnostic and exception messages - things can go wrong in many ways.

**Comment by brando90** [comment]
for my personal needs I am fine with whatever as long as I can clearly distinguish when a `Qed.` type checks (correct proof) vs the current proof attempt does not type check (or any other errors were the proof might need to be restarted or back tracked).

**Comment by ejgallego** [comment]
Yup so we'll try to go for the model that every commands returns `Completed` at the end, and some information about the proof in the middle. It could be a list of objects, an error, some warning, etc...

**Comment by brando90** [comment]
@ejgallego cool. I will assume then that the content of the type checking is before the `(Answer Tag Completed)` message from SerAPI.

**Comment by ejgallego** [comment]
Sounds good!
