### ISSUE TITLE
Roadmap for 0.7.0

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#133]
SerAPI 0.7.0 will target Coq 8.10. As Coq 8.10 is about to enter beta phase, it makes sense to start discussion. From my part, not big changes planned, other than what is already on the Github milestone.

**Comment by ejgallego** [comment]
The 8.10 is almost open for development, I will do a last rebase and then leave the branch alone.

**Comment by palmskog** [comment]
So just to double-check, all ssreflect-related Ltac serialization from #73 should work with 8.10 beta? Should I make a separate PR with tests for that against `v8.10` when `8.10beta1` is out, or sooner?

**Comment by ejgallego** [comment]
@palmskog the 8.10 branch should already include all the tests in #73 if I am not mistaken.

**Comment by ejgallego** [comment]
0.7.0 will happen soon, I plan to merge all remaining PRs first.

**Comment by ejgallego** [comment]
Only blocker issue for 0.7.0 is the integration of the common jsCoq / SerAPI library manager.
