### ISSUE TITLE
pp_ex example broken?

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#147]
Is the following output expected? The README suggests it should return a string.

```
(pp_ex (Print () (CoqConstr (App (Rel 0) ((Rel 0))))))
(Answer pp_ex Ack)
(Answer pp_ex (ObjList ((CoqConstr (App (Rel 0) ((Rel 0)))))))
(Answer pp_ex Completed)
```

**Comment by cpitclaudel** [comment]
(I think the fix is to use `(Print ((pp_format PpStr)) (CoqConstr (App (Rel 0) ((Rel 0)))))` instead)

**Comment by ejgallego** [comment]
I think the output is correct. Optional parameters , such as the output format, are more of a help for debugging than a thing that should be relied upon.

In this case the default output format is set to ppser, so the print command parses the term, and serializes it back. We could indeed change the default (or make it user configurable) however I am more of the opinion that the clients should always provide the desired format.

**Comment by cpitclaudel** [comment]
I just meant that the example in the README is out of sync with what SerAPI outputs ^^ And my second message was to suggest a change to the readme :)  But I know see that I wrote `pp_ex` broken instead of `pp_ex example`; I just clarified the title.

Thanks again for your hard work.

**Comment by ejgallego** [comment]
Thanks for the explanation, indeed I read it wrong.
