### ISSUE TITLE
Allow `Query` to take a `stateid`

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#15]
@cpitclaudel suggests:

> Do you think we could extend Goals to take a state id?

I am not 100% sure how the async Stm interacts with the proof engine. My guess is that the current proof object corresponds to the current Stm `reached` state. This is basically the last observed state.

Thus, we could try something like observe + query, but keep in mind that this could be very expensive!
I don't know if there could be a better way. If you agree I can implement this thou.

An interesting alternative would be to cache the goals object for every reached state. But we would need an Stm callback to do this efficiently. I dunno if the current callbacks in [`stm.mli`](https://github.com/coq/coq/blob/trunk/stm/stm.mli#L184) are enough.

(I guess I'll try to spam @gares again, if he makes me pay a beer for every mention I'll go broke XD)

**Comment by Ptival** [comment]
This would definitely be needed for PeaCoq. In fact, the XML protocol exposes a Query command that takes as input a state ID, in case you're interested in seeing how it's done.

**Comment by ejgallego** [comment]
@Ptival we have the `StmQuery` command, but I don't think this is enough to get the goals. And indeed, it forces an observe.

**Comment by ejgallego** [comment]
Anyways that is a good point, we could just do an observe, get the goals, and go back to the state, though `Stm.query` is ought to be more efficient due to the `Future.purify` (but is enough for not evaluated states?)

**Comment by ejgallego** [comment]
Done. It turns out the STM already exposed exactly what I wanted! Let me know how it works thou, further refinements may be needed.

Also note that `Query` API is a bit of a mess right now, but that doesn't worry me too much. I think we can try to sort the `Control` API out first and then we'll shift our focus to `Querying` effectively.

**Comment by cpitclaudel** [comment]
Looks god! Though I'm getting this:

```
File "sertop/sertop_goals.ml", line 41, characters 17-25:
Error: This pattern matches values of type [? `Error of 'a ]
       but a pattern was expected which matches values of type
         [ `Expired | `Valid of Stm.state option ]
       The second variant type does not allow tag(s) `Error
Command exited with code 2.
make: *** [sertop] Error 10
```

**Comment by ejgallego** [comment]
Umm let me have a look.

**Comment by ejgallego** [comment]
Time to update your Coq! We are on the bleeding edge :S

**Comment by cpitclaudel** [comment]
Spot on

**Comment by cpitclaudel** [comment]
Hmm ok. Now I'm getting error messages about "True" and "intro" not being found in the current environment :/

**Comment by ejgallego** [comment]
You may want to do a `git clean -fxd` in the Coq side, `make clean` on the SerAPI side and rebuild. Unfortunately not all dependencies are properly tracked.

**Comment by cpitclaudel** [comment]
Oooooh I see: the problem was this:

(Feedback
   ((id
     (State 2))
    (contents
     (ErrorMsg
      ((fname "")
       (line_nb 1)
       (bol_pos 0)
       (line_nb_last 1)
       (bol_pos_last 0)
       (bp 15)
       (ep 31))
      "Error: Unable to locate library Coq.Init.Prelude."))
    (route 0)))

I was too eager and didn't recompile the libraries in full.
