### ISSUE TITLE
[serapi] Capitalization convention?

### ISSUE THREAD

**Issue by corwin-of-amber** [ejgallego/coq-serapi#167]
I noticed that `KerName` and `MutInd` are serialized with head symbol `Kername` and `Mutind`, respectively; while `DirPath` is serialized with `DirPath`.

Is there an intentional convention where only the first letter of a symbol is capitalized? And if so, should `DirPath` be changed to `Dirpath`?

**Comment by ejgallego** [comment]
Indeed, that code comes from a very early version and I was pretty careless. I have submitted a PR to fix this.

Note however that still there is not clear agreement Coq upstream on how to tackle serialization for types that are not public [such as these] so we are bound to be a bit ad-hoc :/
