### ISSUE TITLE
Deprecations in the Coq v8.10 branch break the build

### ISSUE THREAD

**Issue by palmskog** [ejgallego/coq-serapi#172]
Some recent commit to Coq's `v8.10` break the build of SerAPI. Specifically, `wit_intropattern` was deprecated in favor of `wit_simple_intropattern` in Ltac. The compilation error:
```shell
File "serlib/plugins/ltac/ser_tacarg.ml", line 426, characters 29-52:
Error (warning 3): deprecated: Ltac_plugin.Tacarg.wit_intropattern Use wit_simple_intropattern
Makefile:19: recipe for target 'build' failed make: *** [build] Error 1
```

Since we are actively using the `v8.10+sertok` branch, I pushed a quick fix there to make it compile again: ee82b9a626

If there is cleaner way to do the fix, I'd be happy to force-push away that one.

**Comment by ejgallego** [comment]
IMHO the fix looks good, please push to the main branch when you want @palmskog

**Comment by palmskog** [comment]
OK, pushed the fix.

**Comment by ejgallego** [comment]
Thanks!
