### ISSUE TITLE
Introduce `Pp.t` helpers

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#184]
Some UIs don't have the ability to render `Pp.t` natively, so we may want to improve things for them so they don't have to call `(Print ...)` to display messages. In particular, there are two constructions that could benefit from having some rendering:
- `CoqExn`
- `Feedback` messages.

cc @andreypopp

**Comment by andreypopp** [comment]
`CoqObj coq_object list` I'm getting as an answer for `Goals` is also what I need to be printed.

**Comment by andreypopp** [comment]
Awesome, I've missed that. Thank you.
