### ISSUE TITLE
[sercomp] Print mode produces broken .v

### ISSUE THREAD

**Issue by artagnon** [ejgallego/coq-serapi#190]
I'm attempting to use sercomp as a formatter for my Coq document. `sercomp --mode print <filename>` produces a `.v` that doesn't compile, when `<filename>` contains `Global Existing Instance ...`; in particular, `sercomp` produces `#[global] ...`, which `coqc` can't process.

**Comment by ejgallego** [comment]
Hi @artagnon , thanks for the report! Indeed see my [comment](https://github.com/ejgallego/coq-serapi/issues/191#issuecomment-568257589) in #191 , SerAPI just calls the Coq printer in this case, so this seems like a Coq bug.

We should report it upstream, can you try with `coqtop -lv file.v` where file.v contains a minimal case of the bug? I'd be great if we could fix that for 8.11

More generally, the only way to get reliable roundtrip at the moment is using the serialize mode.

**Comment by artagnon** [comment]
Hey @ejgallego. It turns out that coq can actually parse `#[global] ...` lines just fine: I'd never seen this syntax, so I assumed the round-tripping was broken. Here's the code I'm using:

```
From Coq.Relations Require Import Relation_Definitions.
From Coq.Classes Require Import RelationClasses Morphisms.

Section Category.
  Reserved Notation "A ~> B" (at level 60).
  Reserved Notation "f ∼ g" (at level 65).
  Reserved Notation "f ∙ g" (at level 55).

  Record Category : Type :=
    mkCategory
      { Obj :> Type
        ; Hom : Obj -> Obj -> Type
          where "A ~> B" := (Hom A B)
        ; Id : forall A, A ~> A
        ; sim : forall {A B}, (A ~> B) -> (A ~> B) -> Prop
          where "f ∼ g" := (sim f g)
        ; sim_equiv : forall {A B}, Equivalence (@sim A B)
        ; composite : forall {A B C}, (A ~> B) -> (B ~> C) -> A ~> C
          where "g ∙ f" := (composite f g)
        ; composite_prop : forall {A B C},
            Proper (@sim A B ==> @sim B C ==> @sim A C) composite
        ; id_left : forall {A B} (f : A ~> B), Id B ∙ f ∼ f
        ; id_right : forall {A B} (f : A ~> B), f ∙ Id A ∼ f
        ; associativity : forall {A B C D} (f : A ~> B) (g : B ~> C) (h : C ~> D),
            h ∙ (g ∙ f) ∼ (h ∙ g) ∙ f
      }.

  Global Existing Instance sim_equiv.
  Global Existing Instance composite_prop.
End Category.
```

After a `sercomp --mode=print`, `coqtop -lv` and `coqc` process it just fine. Sorry for the false lead.

**Comment by ejgallego** [comment]
No worries, yeah indeed Coq 8.10 has moved quite a few command modifiers to "attributes" which have a quite foreign syntax to Coq's vernacular.

This could still be considered a bug as the `Global` to `#[global]` transformation should not be maybe done, but indeed that would have to be fixed in Coq upstream.
