### ISSUE TITLE
Define protocol and batching options for control commands [Was: Question about Acks]

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#2]
Hey Emilio,

IIUC, the current design is that when sending a query the IDE immediately gets an `Ack` with a number. This allows it to track (potentially multiple) future responses to that query.

I wonder if we could do a bit better here. Two suggestions:
- Wouldn't it be nice if one passed an id with each query, and responses used that? This would allow IDEs to fully disconnect query sending and response processing. Concretely, I mean that one could say
  
  ``` lisp
  (Query 15 (((Prefix "Debug")) None PpSexp) Option)
  ```
  
  And get 
  
  ``` lisp
  (Answer 15 Ack)
  (Answer 15 ...)
  ```
- Do I understand correctly that responses can come in chunks? If so, maybe we could have an extra `(Answer 15 Completed)` to indicate that no more output will be produced for a given query (I see there's a Completed constructor in `answer_kind`)? Otherwise, how does one know that all output has been received for a query?
  
  (It could be that I misunderstood and that in fact there's only one reply per message, in addition to the Ack)
- Finally, assuming we let the IDE pick the query ID, could we do entirely without Acks?

Clément.

**Comment by cpitclaudel** [comment]
(I'm also wondering whether IDs would be better as strings instead of numbers)

**Comment by ejgallego** [comment]
Hi Clément thanks for the comments!

- IDE suplying the query ID: What should happen if the IDE reuses a query number? Other than that, it seems a great idea, I see how it makes life easier. Done in 9ae859d , note that the tag (an arbitrary atom) goes first. I could improve that or even make it optional (at the cost of some complexity).

- The current rationale for `Completed` is that it only applies to Control Commands. Control commands are an abstraction for a function call `f : arg -> ret` and  `Completed` takes the role of `f : a -> unit`.

  Queries indeed are intended to return a stream, and may produce more output later. So you could for instance do `(tag (Query Resume))` to implement paging, etc.. So maybe queries could produce something like `NoMoreResults` when they are done. I'd say let's think a bit more on this one, but I'd be tempted to let the IDE know when the query is over with a kind of `NoMore` response to a `Resume` command.

- IMHO acks are useful (and they were requested by Jason). The role of the ack is to allow the consumer to know that Coq has received the command and may be busy. Currently, if you send a command that takes a long time to execute to Coq you'll be left on the dark for a while, it seems.

**Comment by cpitclaudel** [comment]
Hi Emilio,

I'd be fine with making the result of reusing a tag undefined: it's up to IDEs to not make that mistake, either by incrementing a counter or by using UIDs, or any other mechanisms.

Thanks for the explanation about Completed. I think I like the approach that you described.

Regarding Acks: maybe @JasonGross can comment? I'm not sure what information they add (though they don't hurt, of course). In particular, are there any cases in which you wouldn't receive an Ack?

**Comment by ejgallego** [comment]
Cool! Let me know how the current approach works. Keep in mind that I have  ε-experience in IDE design so I'm kind blindly adding stuff.

Regarding `Ack`, in the current design you **always** receive and `Ack`, which means "your command was parsed and delivered to Coq". I guess in most use cases you can ignore them now.

**Comment by JasonGross** [comment]
I'm not sure when/where I requested `Ack`s, but the use-case I probably had in mind was that in the current `-emacs` protocol, there's no way to tell the difference between "the input you sent me is incomplete; I'm waiting for more" verses "please wait while I process your input".  This means that you have to parse the document yourself.  If there's a way to say "Coq, please parse this document for me", then I don't care about `Ack`s for the bug-minimizer.  If the result of getting an incomplete instruction is to immediately return with "your instruction was incomplete", then I also don't need `Ack`s.  (Currently, the way I parse documents is to run `coqc -time` or `coqtop -emacs -time` or similar over the entire document to get character ranges.)

**Comment by ejgallego** [comment]
I see, thanks Jason. I'm refining the semantics of `Acks` and indeed they now mean "You command was parsed successfully by SerAPI", so indeed, IDEs may want to check that an `Ack` is received, incorrect sexp will result in a SexpError.

**Comment by cpitclaudel** [comment]
Thanks for the clarification @JasonGross  and @ejgallego :)

**Comment by ejgallego** [comment]
@JasonGross @cpitclaudel , I've opened issue #5 to try to help with document parsing.

**Comment by ejgallego** [comment]
@JasonGross , I didn't have this application in mind at the beginning, but after thinking for a bit SerAPI could really help the bug minimizer IMVHO. Let me know if you need help with it.

AFAICS, the remaining issue before closing is to decide the exact method for the part of the protocol that adds a sentence. Now, it is synchronous: you always get either an `Error`, with the tag/edit_id you assigned to the input, or one or several `Added` with the position(s) and stateid of the new sentences.

**Comment by ejgallego** [comment]
Ok, that has been decided, `Add` will indeed be asynchronous, that is to say, the client will specify the "id" and all subsequent feedback will use the client-chosen id. `Acks` and `Completed` stay for clients willing to have a bit more information.

Thanks to all for the help and feedback.
