### ISSUE TITLE
Out-of-order error messages

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#201]
Hi Emilio,

Consider the following snippet:

```coq
Section Test.
  Goal False.
    intro.
  Admitted.

  Definition xyz := 1.
  Goal xyz = xyz.
End Test.
```

The `intro` here is invalid; but this is what happens when I feed it to sertop:

```
("query0"("Add"()"Section Test.\n  Goal False.\n    intro.\n  Admitted.\n\n  Definition xyz := 1.\n  Goal xyz = xyz.\nEnd Test.\n"))
(Answer query0 Ack)
(Feedback((doc_id 0)(span_id 9)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 7)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 6)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 5)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 4)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 3)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 2)(route 0)(contents(ProcessingIn master))))
(Feedback((doc_id 0)(span_id 1)(route 0)(contents Processed)))
(Feedback((doc_id 0)(span_id 2)(route 0)(contents Processed)))
(Feedback((doc_id 0)(span_id 3)(route 0)(contents Processed)))
(Feedback((doc_id 0)(span_id 4)(route 0)(contents(Message(level Error)(loc(((fname ToplevelInput)(line_nb 3)(bol_pos 28)(line_nb_last 3)(bol_pos_last 28)(bp 32)(ep 38))))(pp(Pp_string"No product even after head-reduction."))(str"No product even after head-reduction.")))))
(Feedback((doc_id 0)(span_id 7)(route 0)(contents(Message(level Error)(loc(((fname ToplevelInput)(line_nb 7)(bol_pos 75)(line_nb_last 7)(bol_pos_last 75)(bp 82)(ep 85))))(pp(Pp_glue((Pp_string"The reference")(Pp_print_break 1 0)(Pp_string xyz)(Pp_print_break 1 0)(Pp_string"was not found")(Pp_print_break 1 0)(Pp_string"in the current")(Pp_print_break 1 0)(Pp_string environment.))))(str"The reference xyz was not found in the current environment.")))))
(Answer query0(Added 2((fname ToplevelInput)(line_nb 1)(bol_pos 0)(line_nb_last 1)(bol_pos_last 0)(bp 0)(ep 13))NewTip))
(Answer query0(Added 3((fname ToplevelInput)(line_nb 2)(bol_pos 14)(line_nb_last 2)(bol_pos_last 14)(bp 16)(ep 27))NewTip))
(Answer query0(Added 4((fname ToplevelInput)(line_nb 3)(bol_pos 28)(line_nb_last 3)(bol_pos_last 28)(bp 32)(ep 38))NewTip))
(Answer query0(Added 5((fname ToplevelInput)(line_nb 4)(bol_pos 39)(line_nb_last 4)(bol_pos_last 39)(bp 41)(ep 50))NewTip))
(Answer query0(Added 6((fname ToplevelInput)(line_nb 6)(bol_pos 52)(line_nb_last 6)(bol_pos_last 52)(bp 54)(ep 74))NewTip))
(Answer query0(Added 7((fname ToplevelInput)(line_nb 7)(bol_pos 75)(line_nb_last 7)(bol_pos_last 75)(bp 77)(ep 92))NewTip))
(Answer query0(CoqExn((loc(((fname ToplevelInput)(line_nb 7)(bol_pos 75)(line_nb_last 7)(bol_pos_last 75)(bp 82)(ep 85))))(stm_ids((0 7)))(backtrace(Backtrace()))(exn(ExplainErr.EvaluatedError"The reference xyz was not found in the current environment."))(pp(Pp_glue((Pp_glue((Pp_glue((Pp_glue((Pp_string"The reference")(Pp_print_break 1 0)(Pp_string xyz)))(Pp_print_break 1 0)(Pp_string"was not found")))(Pp_print_break 1 0)(Pp_string"in the current")))(Pp_print_break 1 0)(Pp_string environment.))))(str"The reference xyz was not found in the current environment."))))
(Answer query0 Completed)
```

Note how it reports an "ExplainErr.EvaluatedError" about a missing name (`"The reference xyz was not found in the current environment."`) instead of reporting the error due to the bad "intro".

If I then run the `exec` queries one by one I do get the right report:

```
("query3"("Exec""2"))
(Answer query3 Ack)
(Feedback((doc_id 0)(span_id 2)(route 0)(contents Processed)))
(Answer query3 Completed)
("query5"("Exec""3"))    
(Answer query5 Ack)
(Feedback((doc_id 0)(span_id 3)(route 0)(contents Processed)))
(Answer query5 Completed)
("query8"("Exec""4"))
(Answer query8 Ack)
(Feedback((doc_id 0)(span_id 4)(route 0)(contents Processed)))
(Answer query8(CoqExn((loc(((fname ToplevelInput)(line_nb 3)(bol_pos 28)(line_nb_last 3)(bol_pos_last 28)(bp 32)(ep 38))))(stm_ids((3 4)))(backtrace(Backtrace()))(exn(CErrors.UserError("""No product even after head-reduction.")))(pp(Pp_string"No product even after head-reduction."))(str"No product even after head-reduction."))))
(Answer query8 Completed)
```

It's expected that results aren't reliable past the first error, of course, but what surprised me in this example is that a late (invalid) error, caused by the real error that comes earlier, is reported first.

**Comment by ejgallego** [comment]
This is due to the Coq document manager not considering the first error fatal, due to error recovery. Note how the error does indeed appear in the feedback message.

One solution is to disable the error recovering mechanism; I think we already do this in `sercomp`.

You could try to rely on feedbacks as to recognize errors, but I am not sure this is 100% reliable, in previous Coq versions indeed Coq was quite buggy in this sense and some error feedbacks were missing due to a bit messy error handling implementation in the stm c.f. https://github.com/coq/coq/issues/5479

**Comment by cpitclaudel** [comment]
> One solution is to disable the error recovering mechanism; I think we already do this in sercomp. 

Having an option for this would be perfect.

> You could try to rely on feedbacks as to recognize errors, but I am not sure this is 100% reliable

One difficulty is that the feedbacks come before the "Added" messages

**Comment by ejgallego** [comment]
> Having an option for this would be perfect.

Sounds good, will add to 0.11.1

> > You could try to rely on feedbacks as to recognize errors, but I am not sure this is 100% reliable
> 
> One difficulty is that the feedbacks come before the "Added" messages

Indeed, the current protocol is too complex. In jsCoq we use `newtip` systematically so we choose the id and don't have to wait for `Added`, but this unfortunately rules out cases where Coq doesn't respect the `newtip` parameter c.f. https://github.com/jscoq/jscoq/issues/129

Still a rework of the protocol is planned [and making good progress] but yeah, not before 8.13 :S

**Comment by cpitclaudel** [comment]
> Sounds good, will add to 0.11.1

Thanks a lot!
