### ISSUE TITLE
Add `ontop` option seems to be not supported

### ISSUE THREAD

**Issue by rashchedrin** [ejgallego/coq-serapi#202]
I want to work with different proof branches. It seems that option `ontop` of `Add` command is designed specifically for this use case, however, when I try to use it it says that `"Stm.add called for a different state (4) than the tip: 5. This is not supported yet, sorry."`. Here's input to reproduce this message:
```
(Add () "Variables A B C : Prop.")
(Exec 2)
(Add () "Goal (A -> B -> C) -> (A -> B) -> A -> C.")
(Exec 3)
(Add () "intro H.")
(Exec 4)
(Add () "intros HStateFive HA.")
(Exec 5)
(Exec 4)
(Add ((ontop 4)(newtip 51)) "intros HStateFiftyOne HA.")
```
Here's the complete output of this sequence:
https://gist.github.com/rashchedrin/3584eaa4316dc670947bf5501a031a7b
(I entered them in command prompt of `rlwrap sertop --printer=human`)
My version of sertop is 8.11.0+0.11.0 .
The last `(Exec 4)` command doesn't change anything: I've tried with and without it with the same result. I've also tried it with and without --deep-edits flag (I have no idea what it does), result is the same. 
If there is any workaround for this, please tell me, because utilizing branch switching for faster ATP is the main focus of my work right now.

**Comment by ejgallego** [comment]
Hi @rashchedrin , indeed this is not supported upstream; unless you are on an "Edit" branch, which we don't really support, I think Coq can only have one document, so you if you have a document:
```
s1 <- s2 <- s3
```
and you want to do `s1 <- s2 <- s4` you need to cancel `s3` first, at least with the current setup.

I propose a different solution for you use case, in PR #210 . With that PR, you can actually call `(Fork ...)` when constructing `s2`, and then proceed in parallel with two `sertop` processes.

How well that will work is unknown, but it could indeed work pretty well. Would you mind testing / reviewing that PR? I can merge it if that will make your testing easier.

**Comment by rashchedrin** [comment]
Thank you for implementing this! This might be a game changer for me. I'll take a closer look at it after 2-3 days (I need to finish some of my experiments first).

**Comment by ejgallego** [comment]
Will release the `Fork` workaround in 0.12.1, full speculative execution is delayed to the next-gen engine.
