### ISSUE TITLE
!pinned flag should not be used in opam package for releases

### ISSUE THREAD

**Issue by palmskog** [ejgallego/coq-serapi#208]
The `!pinned` flag is currently used in the version-tracked opam package definition (`coq-serapi.opam`).

However, this flag seemingly causes CI failures in the upstream opam repository, so it should never be part of opam package definitions for released versions of SerAPI (that are submitted to this opam repo). This should be accomplished with release automation, to avoid having to manual edit the opam file.

Some more background: ocaml/opam-repository#16564

**Comment by ejgallego** [comment]
Thanks for the report @palmskog , note the comment of @kit-ty-kate here too:
https://github.com/ocaml/opam-repository/pull/15850#discussion_r380142221

> Apparently opam does not support !pinned (but does pinned):
>   [ERROR] undefined filter variable in dependencies of coq-serapi.8.11.0+0.11.0: pinned

It is a bit unclear to me how to best solve this, ideally I would not have to add some extra release step to the current standard `dune-release` workflow.

**Comment by ejgallego** [comment]
The error seems to have evolved in the latest release, we now just get Coq not installed in OPAM's CI due to the package being pinned? https://github.com/ocaml/opam-repository/pull/17070#issuecomment-681732257
