### ISSUE TITLE
Workaround position reporting for UTF-8 scripts

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#21]
We'd like to do correct location reporting for UTF-8 scripts. See https://coq.inria.fr/bugs/show_bug.cgi?id=4965 for more details.

**Comment by Ptival** [comment]
A bit unrelated: Is there a name for the decimal-encoded bytes that Coq seems to use?

i.e. how do I go from "\206\179" to "γ" in JavaScript? :-)

**Comment by cpitclaudel** [comment]
@Ptival This is Utf8. [206 179] is [0xCE 0xB3], which is the Utf-8 encoding of γ (http://graphemica.com/%CE%B3)

**Comment by ejgallego** [comment]
@Ptival out of curiosity, which command produced that output?

**Comment by cpitclaudel** [comment]
(No idea how this works in JS, but here's a python snippet:)

```bash
$ python3 -c 'print (bytes([206, 179]).decode("utf-8"))'
γ
```

**Comment by Ptival** [comment]
@cpitclaudel yeah I realized it was UTF-8, but can't seem to lookup for UTF-8 decoding libraries that don't assume the `\uCEB3` encoding over this decimal encoding...

@ejgallego For instance:

`(Control (StmAdd () "From Coq Require Import Utf8. Lemma l: ∀ x:nat, ∀ γ: bool, x = γ."))(Control (StmObserve 3))`

**Comment by ejgallego** [comment]
I see, thanks @Ptival ; unfortunately our serializer of choice, `sexplib`, escapes strings to an ASCII, textual format. I am not sure whether this is unfortunate or not.

**Comment by ejgallego** [comment]
I dunno what to do here, I'd rather not re-implement sexplib printer, however having to unescape string seems painful, I guess we'd like SerAPI to be UTF-8 based, right ?.

I think I'll try to rise this issue with sexplib upstream and see what they think.

**Comment by ejgallego** [comment]
BTW, Ocaml provides `Scanf.unescaped` to unscape the strings.

**Comment by ejgallego** [comment]
See also janestreet/sexplib#18

**Comment by Ptival** [comment]
Yeah, I don't think you need to change anything about this. I just need to find a way to convert it back on my end...

Sorry for this derailing of the issue! :-o

**Comment by ejgallego** [comment]
@cpitclaudel note that the byte sequence you get is indeed the one representing the encoded utf symbol:
```
python3 -c 'print (bytes([92, 50, 48, 54, 92, 49, 52, 55]).decode("utf-8"))' 
```
Thus the problem @Ptival is discussing is how to go from the byte sequence `[92, 50, 48, 54, 92, 49, 52, 55]` to indeed `[206,179]`.

@Ptival , I think how SerAPI is going to handle UTF-8 is an important issue and your comment totally fits in this issue, thanks for the feedback!

**Comment by ejgallego** [comment]
Still undecided what is the best way to proceed here. Note that in Ocaml strings are often used to contain binary data, thus sexplib's choice of serialization for non-printable characters makes sense.

**Comment by ejgallego** [comment]
https://github.com/janestreet/sexplib/blob/master/src/lexer.mll#L129 gives the specification that a sexplib deserializer must implement.

**Comment by ejgallego** [comment]
coq-lsp does this correctly, it wasn't trivial at all :S
