### ISSUE TITLE
Minor request: use -Q DIR LP instead of -Q DIR,LP?

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#215]
I'm not sure what the proper way is to do this without breaking existing code.  It's just a bit unfortunate that SerAPIs options are not spelled the same as Coq's

**Comment by ejgallego** [comment]
It is indeed a big pain, I tried to have `cmdliner` to parse that, but I didn't manage to hack a solution where `cmdliner` would take the arguments in this way, I'll try to re-hack to see what can be done [patches welcome of course]

A likely easier solution would be to have Coq itself take `-R log=dir`

**Comment by ejgallego** [comment]
coq-lsp auto-configures itself if passed the correct root, so this is less of an issue.
