### ISSUE TITLE
How is SerAPI different from interacting with Proof General?

### ISSUE THREAD

**Issue by brando90** [ejgallego/coq-serapi#218]
I recently saw this github page https://github.com/ML4PG/ML4PG/issues/1 which provides some sort of statistics analysis of proofs using proof general and maltab.

I am curious, why didn't SerAPI implement some sort of interaction with Coq using proof general (the way that library ML4PG does, forget the statistics).

(I know CoqGym exists, I am just curious why SerAPI didn't use proof general like ML4PG).

**Comment by brando90** [comment]
> There's a bit of confusion here, I think. PG is an IDE that uses an outdated API (coqtop) to retrieve data from Coq. ML4PG is built on top of PG because PG provided a marginally better API than plain coqtop. SerAPI is a much newer (and more pleasant) API to communicate with Coq. PG should be updated to use SerAPI — noth the other way around ^^
> 
> Think of SerAPI as a Coq-specific language server, and PG as an IDE.

Thanks for the information provided!

I am curious, why do you think PG is outdated? 

I am also curious, how is SerAPI much better than CoqTop and PG?

Thanks for your reply.

**Comment by cpitclaudel** [comment]
> I am curious, why do you think PG is outdated?

PG isn't outdated, it's *built on* an outdated protocol (coqtop).

> I am also curious, how is SerAPI much better than CoqTop 

SerAPI is a structured protocol; coqtop is plain text.  

> and PG?

You're comparing apples to oranges here.  It's like asking whether visual studio code is better than the rust language server.

Cheers.

**Comment by palmskog** [comment]
My only addition here would be that SerAPI is not just a protocol, but a way to expose Coq data structures to the external world. In fact, several of the machine learning applications linked in SerAPI's README.md do not use the SerAPI protocol at all.

With that, I believe @cpitclaudel has answered quite definitively the key questions in this issue, so I think it's time to close it.

**Comment by brando90** [comment]
> My only addition here would be that SerAPI is not just a protocol, but also a way to expose Coq data structures to the external world. In fact, several of the machine learning applications linked in SerAPI's README.md do not use the SerAPI protocol at all.
> 
> With that, I believe @cpitclaudel has answered quite definitively the key questions in this issue, so I think it's time to close it.

I'm curious. What do you specifically mean that SerAPI exposes the "data structures"? Perhaps of my arguably (very) shallow understanding of Coq, the only data structures I can think of as any language server exposing is the Proof Terms. Is it what you mean that it exposes proof terms as AST (or something like that)?

**Comment by palmskog** [comment]
I'm not sure what can be added to the following line at the top of the README:
> SerAPI provides automatic serialization of Coq's internal OCaml datatypes from/to JSON or S-expressions (sexps).

For more details on the extent of what has practically been (de)serialized using SerAPI, I suggest you take a look at the [ASE '19 paper](https://users.ece.utexas.edu/~gligoric/papers/CelikETAL19mCoq.pdf) and the [IJCAR '20 paper](https://arxiv.org/abs/2004.07761).
