### ISSUE TITLE
Commas in s-expressions: string or unquote?

### ISSUE THREAD

**Issue by Ptival** [ejgallego/coq-serapi#22]
It seems sexplib sometimes omits quotes around PCData content when the string contains no whitespace.

This became a problem for me when the string was:

`(PCData ,) -- for (PCData ",")`

As my s-expression parsing library of choice ( https://www.npmjs.com/package/s-expression ) seems to expect the comma to be an `unquote`.

Who is to blame here, if anyone? :-)

**Comment by ejgallego** [comment]
Indeed, sexplib serializes data in a particular way. The base data type, quoting from: https://github.com/janestreet/sexplib/blob/master/src/type.ml is
```ocaml
type t = Atom of string | List of t list
```
Thus, the choice is really what to do with strings!

For that, sexplib uses the code at
https://github.com/janestreet/sexplib/blob/master/src/pre_sexp.ml#L22
to guess when it should add quotes, as to make the output more "sexpy"-friendly.

Unfortunately the comma is not there, so I wonder what is the best solution here; I am not an expert on S-expressions myself, but I will definitively try to bring this issue with sexplib developers.

**Comment by ejgallego** [comment]
@cpitclaudel , will this comma thing create problems in emacs?

**Comment by ejgallego** [comment]
Ok, a53964e should provide a more sensible escaping if `--custom-escape` is passed: we treat every Atom as a UTF-8 string. Also, naked commas should not be produced.

Would you mind testing the comma part? Thanks

**Comment by cpitclaudel** [comment]
I think it will be an issue in Emacs as well, yes; `,` is taken by the lisp reader to be a reader macro expanding to `unquote`.

Then again, it shouldn't be very hard to write a separate parser in list; but it would be nice to use the off-the-shelf one. The surprising thing is that Sexplib doesn't distinguish between symbols and strings.

**Comment by ejgallego** [comment]
@cpitclaudel , any other special character we should keep in mind?

`--custom-escape` should solve the comma issue. I'm happy having our printer.

Indeed sexplib makes the choice of "everything is a symbol".

**Comment by cpitclaudel** [comment]
Hmm. I think only quote, backslash, comma, backtick, and `#'`.

**Comment by ejgallego** [comment]
Cool thanks, I'm gonna ask upstream about the quoting. It seems that double quote and backslash are OK.

The rest don't seem OK, I'll fix them in `--custom-escape`, while I get an answer from sexplib upstream.

Comma, quote, and backtick should be escaped only if at the beginning of a symbol, right?
What about `#'`?

I couldn't find a elisp grammar/lexical conventions.

**Comment by ejgallego** [comment]
== How to test sexplib quoting ==
Install utop and sexplib using OPAM, then:
```ocaml
$ utop 
# #require "sexplib";;
# open Sexplib.Sexp;;
# let p x = pp Format.std_formatter (Atom x);;
# p ",";;
```

**Comment by cpitclaudel** [comment]
>Comma, quote, and backtick should be escaped only if at the beginning of a symbol, right?
>What about #'?

No, anywhere in a symbol. Same for `#'` (and there's actually `#<` and `##` as well apparently, though just escaping # would fix that too.

**Comment by cpitclaudel** [comment]
I wonder why sexplib doesn't simply use quotes for everything that is a string on the OCaml side, and symbols for the rest.

**Comment by ejgallego** [comment]
What do you mean by "everything that is a string on the OCaml side" ?

For sexplib, everything is a string, so it would then print `("Control" ("StmAdd" () "Command"))`, etc...

**Comment by cpitclaudel** [comment]
Is `Control` a string? I thought it was the name of a constructor.

**Comment by ejgallego** [comment]
At the sexp-level, `Control` is indeed a string. Recall the sexp syntax:
```
type t = Atom of string | List of t list
```
so sexplib expressions are just possibly nested lists of strings.

**Comment by cpitclaudel** [comment]
Ah, right.

Maybe it would be simpler to just quote everything?

**Comment by ejgallego** [comment]
Maybe we should quote everything, would that be a problem for emacs?

The new printer has been committed, I will close this once I add the proper documentation.

**Comment by cpitclaudel** [comment]
Quoting everything would be totally fine :)

**Comment by Ptival** [comment]
I no longer have a problem with `(PCData ,)`, but I have a problem with `(PCData fold')`.

**Comment by ejgallego** [comment]
@Ptival understood, will fix.

**Comment by riswords** [comment]
Can square braces also be quoted? In `(Query () (Vernac "Print nat."))` for example, I see `(Pp_string ])` which causes an error for the emacs parser.

**Comment by ejgallego** [comment]
@riswords , sure, I'll take of it.

**Comment by ejgallego** [comment]
Should be better now, note that we currently depend on coq/coq#822 due to them having broke its linking spec.

**Comment by ejgallego** [comment]
See	e2982c1 if you need to tweak escaping more, and of course submit a pull request!

**Comment by riswords** [comment]
Great, thank you!

**Comment by ejgallego** [comment]
NP, let me know if you have any additional trouble, note also that we have a gitter channel that may work well for concrete questions.

**Comment by Ptival** [comment]
Ha, just got bit by `(PCData [)` and `(PCData ])` myself!

**Comment by ejgallego** [comment]
Yup at some point we'll make the custom quoting the default.
