### ISSUE TITLE
Protocol documentation link in the README is broken

### ISSUE THREAD

**Issue by ApolloLiZhaoyu** [ejgallego/coq-serapi#226]
Hi, protocol documentation link in the README is broken, hope that you can fix it. Thanks!

**Comment by HKalbasi** [comment]
+1
Please fix it or make an alternative way for reading documentations.

**Comment by tchajed** [comment]
Seems like it's now at https://ejgallego.github.io/coq-serapi/coq-serapi/Serapi_protocol/index.html
