### ISSUE TITLE
Support for 8.13?

### ISSUE THREAD

**Issue by gmalecha** [ejgallego/coq-serapi#227]
We're using Alectryon which depends on this.

**Comment by ejgallego** [comment]
Will update soon, sorry for the delay.

**Comment by jhaag** [comment]
Is there any movement on this?

**Comment by ejgallego** [comment]
@jhaag the current 8.13 branch is almost functional, only critical bit missing now is the manual update of new generic arguments added upstream ; more details on issue #82 , but this is just an annoying and error prone manual process, but other than that quite straightforward.

**Comment by ejgallego** [comment]
Closed by #232
