### ISSUE TITLE
Elusive error location

### ISSUE THREAD

**Issue by Ptival** [ejgallego/coq-serapi#23]
I'm not sure whether this is a coq-serapi bug as much as a Coq protocol bug, but here it is.

When I enter the following sentence in CoqIDE-8.5pl1:

```
Theorem test : let (x, y) = (1, 2) in x.
```

I get an error message, and the `=` sign gets highlighted as the location of the error.

Now, when I enter the same sentence in sertop, all I get is a `CoqExn` with the same error message, but I don't get a `Message` with error location.

I'm not sure where I'm supposed to get this error location from...

```
(Control (StmAdd () "Theorem test : let (x, y) = (1, 2) in x."))
(Answer 51 Ack)
(Answer 51(CoqExn(Stream.Error"[return_type] expected (in [constr:binder_constr])")))
(Answer 51 Completed)
```

Help! :-)

**Comment by ejgallego** [comment]
Good point, investigating....

**Comment by ejgallego** [comment]
Good catch! This is a SerAPI bug in the code that simulates multi-sentence parsing. As coq/coq#204 was not merged, we must simulate multi sentence parsing by actually parsing twice, one time to get the location information, the second time to add the information to the Stm.

I will fix it ASAP.
