### ISSUE TITLE
Nix expression for coq-serapi

### ISSUE THREAD

**Issue by nyraghu** [ejgallego/coq-serapi#241]
I am trying to install coq-serapi in nix-shell.  As coq-serapi is not in nixpkgs, I am writing the necessary Nix expression myself.  Here is what I have tried:
``` Nix
{ lib, coq, fetchTarball }:

assert (
  lib.versionAtLeast coq.version "8.13.0"
  &&
  lib.versionOlder coq.version "8.14"
);

let
  ocamlPackages = coq.ocamlPackages;
in
ocamlPackages.buildDunePackage {
  pname = "coq-serapi";
  version = "8.13.0+0.13.0";

  src = fetchTarball {
    url = "https://github.com/ejgallego/coq-serapi/releases/download/8.13.0%2B0.13.0/coq-serapi-8.13.0.0.13.0.tbz";
    sha256 = "0k69907xn4k61w4mkhwf8kh8drw9pijk9ynijsppihw98j8w38fy";
  };

  useDune2 = true;

  buildInputs =
    [ coq ] ++ (with ocamlPackages; [
      cmdliner
      dune_2
      findlib
      ocaml
      ppx_deriving
      ppx_deriving_yojson
      ppx_import
      ppx_sexp_conv
      sexplib
      yojson
      zarith
    ]);

  propagatedBuildInputs =
    [ coq ] ++ (with ocamlPackages; [
      cmdliner
      dune_2
      findlib
      ocaml
      ppx_deriving
      ppx_deriving_yojson
      ppx_sexp_conv
      sexplib
      yojson
      zarith
    ]);
}
````
I am using the following shell.nix file for the nix-shell environment:

``` Nix
let
  nixpkgs = import <nixpkgs> {};
  coq = nixpkgs.coq;
  ocamlPackages = with coq.ocamlPackages; [ dune_2 findlib ocaml zarith ];
  coq-serapi = import ./coq-serapi.nix {
    inherit (builtins) fetchTarball;
    inherit (nixpkgs) lib coq;
  };
in nixpkgs.mkShell {
  buildInputs = [ coq coq-serapi ] ++ ocamlPackages;
}
```

Now when I run `nix-shell`, I get the following error:

``` shell
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Migrate_parsetree__Migrate_parsetree_versions referenced from /nix/store/dgxpggcx37i0bshnykcfrnsx1q44xm08-ocaml4.10.2-ppx_import-1.8.0/lib/ocaml/4.10.2/site-lib/ppx_import/ppx_import.cmxa(Ppx_import__Ppx_types_migrate),
           /nix/store/dgxpggcx37i0bshnykcfrnsx1q44xm08-ocaml4.10.2-ppx_import-1.8.0/lib/ocaml/4.10.2/site-lib/ppx_import/ppx_import.cmxa(Ppx_import)
         Migrate_parsetree__Migrate_parsetree_driver referenced from /nix/store/dgxpggcx37i0bshnykcfrnsx1q44xm08-ocaml4.10.2-ppx_import-1.8.0/lib/ocaml/4.10.2/site-lib/ppx_import/ppx_import.cmxa(Ppx_import)
                        
builder for '/nix/store/45cy3mz0hsjicwwdhvjkbzmqlv9fzj5f-ocaml4.10.2-coq-serapi-8.13.0+0.13.0.drv' failed with exit code 1
error: build of '/nix/store/45cy3mz0hsjicwwdhvjkbzmqlv9fzj5f-ocaml4.10.2-coq-serapi-8.13.0+0.13.0.drv' failed
```
Can you please help?  Thanks.

@Zimmi48

**Comment by Ptival** [comment]
Hi,

I also have interest in building a Nix expression for coq-serapi, though I have been unsuccesful recently.

You can add the `ocaml-migrate-parsetree` library to your `buildInputs`: it is available under, say, `ocamlPackages.ocaml-migrate-parsetree-1-8`.

I have been encoutering more errors down the line, but I will share my current status of broken expressions with you if it can help you push further!

My `coq-serapi.nix` expression looks like:

```nix
{ buildDunePackage
, lib
, src

, cmdliner
, coq
, ocaml-migrate-parsetree
, ppx_deriving_yojson
, ppxlib
, ppx_import
, ppx_sexp_conv
, sexplib
, zarith

}:

buildDunePackage rec {

  pname = "coq-serapi";
  version = src.rev;

  minimumOCamlVersion = "4.07";
  useDune2 = true;

  inherit src;

  buildInputs = [
    # camlp5
    cmdliner
    coq
    ocaml-migrate-parsetree
    ppx_deriving_yojson
    ppxlib
    ppx_import
    ppx_sexp_conv
    sexplib
    zarith
  ];

  meta = with lib; {
    homepage = https://github.com/ejgallego/coq-serapi;
    description = "SerAPI is a library for machine-to-machine interaction with the Coq proof assistant";
    license = licenses.lgpl21Plus;
    maintainers = [ maintainers.ptival ];
  };

}
```

and my `shell.nix` that calls it contains the following:

```nix
{
  ocamlPackages = nixpkgs.ocaml-ng.ocamlPackages_4_07;

  ppx_sexp_conv = ocamlPackages.buildOcamlJane {
    name = "ppx_sexp_conv";
    hash = "04npb8x5bhrpg73lrg7aq0qcw0w20rd80w0v6849vpbp3yxsabwd";
    propagatedBuildInputs = with ocamlPackages; [ ppx_core ppx_tools ppx_type_conv sexplib ];
    version = sources.ppx_sexp_conv.rev;
  };

  coq-serapi = ocamlPackages.callPackage ./coq-serapi/default.nix {
    coq = nixpkgs.coq_8_12;
    ocaml-migrate-parsetree = ocamlPackages.ocaml-migrate-parsetree-1-8;
    inherit ppx_sexp_conv;
    src = sources.coq-serapi;
  };
}
```

Again, these do **not** work! I'm getting a `configure` error on the `ppx_sexp_conv` package.

Feel free to share your progress here if you get past the ocaml-migrate-parsetree error, I'd be happy to keep helping you debug it until we figure out whether this is feasible.

**Comment by Zimmi48** [comment]
Unfortunately, I don't know enough about the ppx ecosystem to understand what's going on here. I also find it surprising that adding `ocaml-migrate-parsetree` to the build inputs would change anything given that it's already a propagated build input of `ppx_import`... cc @vbgl

**Comment by nyraghu** [comment]
Thanks for the reply.  I'll just use `opam` while this issue is pending.

**Comment by ejgallego** [comment]
Thanks for the work on this; the problem here is that nix is not aware of the versioning constraints for `ppxlib` and `ocaml-migrate-parsetree`, indeed they are complex, and it seems you happen to be installing two incompatible versions.

I'm afraid I don't understand at all how version selection works in Nix, so I can't be of more help, but I'd say that a safe choice for SerAPI these days is `0.15.0` + ' 1.8.0` , until the new version of ppx_import is released which should allow us to migrate to OMP 2.0

**Comment by Zimmi48** [comment]
So as I understand it, `ppx_import` is stuck at OMP 1.8 but `ppx_deriving` has moved forward. When combining both, one should make sure to override the version of `ppxlib` that `ppx_deriving` depends on so that OMP 1.8 and not 2.1 is used.

This is what is done for elpi for instance:

```nix
    elpi = callPackage ../development/ocaml-modules/elpi (
      let ppxlib_0_15 = if lib.versionAtLeast ppxlib.version "0.15"
        then ppxlib.override { version = "0.15.0"; }
        else ppxlib; in
      {
        ppx_deriving = ppx_deriving.override { ppxlib = ppxlib_0_15; };
        ppxlib = ppxlib_0_15;
      }
    );
```

We can override the ppxlib version for the whole `coq.ocamlPackages` set by doing:

```nix
let ocamlPackages =
      coq.ocamlPackages.overrideScope'
        (self: super: { ppxlib = super.ppxlib.override { version = "0.15.0"; }; });
in
```

However, in the case of SerAPI, one also needs to override `ppx_sexp_conv` to put it at version 0.14.1, which is compatible with ppxlib 0.15.0. And I can't seem to figure out how to override its version (probably because this package is part of the `janeStreet` package set). @sternenseemann might know how to do this.

Another solution is simply to override the `ocamlPackages` version of Coq to put it at 4.07, but this is unsatisfying if the goal is to put SerAPI in nixpkgs.

**Comment by ejgallego** [comment]
An even easier path may be to wait for the new version of ppx_import, and require it; it has been ported to omp 2.0 , and I am almost done with testing it, so a release could happen soon.

**Comment by ejgallego** [comment]
Tho how come nix installs packages that are not "compatible", is there not a version constraint resolution step?

**Comment by sternenseemann** [comment]
> However, in the case of SerAPI, one also needs to override `ppx_sexp_conv` to put it at version 0.14.1, which is compatible with ppxlib 0.15.0. And I can't seem to figure out how to override its version (probably because this package is part of the `janeStreet` package set). @sternenseemann might know how to do this.

We don't have an intended way to switch the version of `ppx_sexp_conv` atm, so there are mostly two options:

* Override the `src` attribute of `ppx_sexp_conv`. This sort of works via `overrideAttrs`, but `janePackage` hasn't been written with overriding in mind, so this is somewhat ugly (for example it refuses to let you change its version).
* Introduce another attribute with the desired version in nixpkgs

If you only need the nix expression only outside of nixpkgs, you could also use a version of nixpkgs before the ppxlib update(s) which was sometime late last year, I think.

**Comment by Zimmi48** [comment]
> If you only need the nix expression only outside of nixpkgs, you could also use a version of nixpkgs before the ppxlib update(s) which was sometime late last year, I think.

I don't know about the others, but my own goal was to package SerAPI in nixpkgs (and package Alectryon next). So this is not an option.

>Tho how come nix installs packages that are not "compatible", is there not a version constraint resolution step?

There is no version constraint and thus no constraint resolution in Nix.

>An even easier path may be to wait for the new version of ppx_import, and require it; it has been ported to omp 2.0 , and I am almost done with testing it, so a release could happen soon.

OK, good to know!

**Comment by nyraghu** [comment]
> An even easier path may be to wait for the new version of ppx_import, and require it; it has been ported to omp 2.0 , and I am almost done with testing it, so a release could happen soon.

Thanks @ejgallego, that's what I will do, and use `opam` meanwhile.

**Comment by Zimmi48** [comment]
Thanks to the advice of @ejgallego and @sternenseemann, I've managed to reach a state where SerAPI properly builds. The installation doesn't look correct yet (`sertop --help` works but `sertop` alone fails with an exception) but this might be at a stage where others can take over. Here it is: https://github.com/Zimmi48/nixpkgs/commit/b18b3d12e7d67f45577281958b095efa0e3e753e.

**Comment by nyraghu** [comment]
> I don't know about the others, but my own goal was to package SerAPI in nixpkgs (and package Alectryon next). So this is not an option.

@Zimmi48, that was my intention too, though I was only interested in packaging `coq-serapi` and `alectryon` for my own use because I don't have sufficient Nix experience to package stuff for nixpkgs.  Anyway I have written a [Nix expresson for alectryon](https://github.com/nyraghu/ixnay/blob/master/alectryon/default.nix).   (It would have been convenient if `alectryon` was a `pypi` package or used `setuptools`).  If you could look at it,  please let me know if there are any errors or things that need improvement.     Thanks.

**Comment by ejgallego** [comment]
Thanks a lot for all the work folks, amazing stuff; sadly ppx_import 2.0 seems to still have some issues, no idea on the ETA to solve them :(

> Thanks to the advice of @ejgallego and @sternenseemann, I've managed to reach a state where SerAPI properly builds. The installation doesn't look correct yet (sertop --help works but sertop alone fails with an exception) but this might be at a stage where others can take over.

What exception are you getting? Most likely is due to lack of registration with the ocamfind-based plugin loader?

This is an area Nix was quite messing things IIRC.

**Comment by Zimmi48** [comment]
> Most likely is due to lack of registration with the ocamfind-based plugin loader?

Very likely indeed. The exception is:

```
sertop: internal error, uncaught exception:
        Fl_package_base.No_such_package("coq-serapi.serlib.ground_plugin", "")
```

**Comment by Zimmi48** [comment]
> Anyway I have written a [Nix expresson for alectryon](https://github.com/nyraghu/ixnay/blob/master/alectryon/default.nix). (It would have been convenient if `alectryon` was a `pypi` package or used `setuptools`.

Cool! Note that the PyPI / setuptools question is being worked on: see https://github.com/cpitclaudel/alectryon/pull/46. I'm not really competent on writing Nix expressions for Python packages, so I cannot really give any suggestions for improvements.

**Comment by ejgallego** [comment]
> Very likely indeed. The exception is:

That is indeed, SerAPI does use ocamlfind to load the serialization plugins, so they must appear in `ocamlfind list`; I understand Nix does extend `OCAMLPATH` to do that, so you may need to add it to the recipe so they are in scope.

**Comment by ejgallego** [comment]
Let me write a more friendly error message by the way.

**Comment by Zimmi48** [comment]
Thanks to the help of @ejgallego, I have finally managed to package SerAPI (and Alectryon) for nixpkgs. See https://github.com/NixOS/nixpkgs/pull/134454.

**Comment by ejgallego** [comment]
Amazing thanks! Just wondering, would you like to add the nix development infrastructure to the repos?

**Comment by Zimmi48** [comment]
Now that SerAPI is in nixpkgs, this infrastructure can be configured very simply. I can add it if there are people who are interested in this.

**Comment by ejgallego** [comment]
Ok, great @Zimmi48 , I guess maybe you can push a commit to `README.md` closing this issue then?

**Comment by Zimmi48** [comment]
OK, will do.

**Comment by Zimmi48** [comment]
Actually, there still is an issue with the Nix package, that can be observed when doing the following:

```
$ nix-shell -p coq coqPackages.equations coqPackages.serapi
$ sertop --printer=human
```

We get the following message:

```
(Feedback
 ((doc_id 0) (span_id 0) (route 0)
  (contents
   (Message (level Warning) (loc ())
    (pp
     (Pp_glue
      ((Pp_string
        "Cannot open /nix/store/c6xzbdg3clahmz2kli6i55b4zm07lldz-coq-8.13.2/lib/coq//nix/store/y7yakr8rqhwzfwhv4d1ihj1ijg945yg0-coq8.13-equations-1.2.4+coq8.13/lib/coq/8.13/user-contrib/")
       (Pp_print_break 1 0) (Pp_string [cannot-open-path,filesystem]))))
    (str
      "Cannot open /nix/store/c6xzbdg3clahmz2kli6i55b4zm07lldz-coq-8.13.2/lib/coq//nix/store/y7yakr8rqhwzfwhv4d1ihj1ijg945yg0-coq8.13-equations-1.2.4+coq8.13/lib/coq/8.13/user-contrib/\
     \n[cannot-open-path,filesystem]")))))
```

where we discover that `COQPATH` isn't correctly interpreted (paths are interpreted as being relative to the Coq root instead of being absolute).

FTR:

```
$ echo $COQPATH 
/nix/store/y7yakr8rqhwzfwhv4d1ihj1ijg945yg0-coq8.13-equations-1.2.4+coq8.13/lib/coq/8.13/user-contrib/
```

I'm not aware of there being any use case for interpreting `COQPATH` relative to the Coq root.

**Comment by Zimmi48** [comment]
Proposed fix at #249.

**Comment by praalhans** [comment]
@Zimmi48 thanks for providing a Nix package! After installing the package in my user profile using

````
$ nix-env -iA nixos.coqPackages.serapi
````

and then running sertop,

````
$ sertop
````

results again in the error:

````
sertop: internal error, uncaught exception:
        Fl_package_base.No_such_package("coq-serapi.serlib.ground_plugin", "")
````

However, as indicated, when I open a nix-shell using the command:

````
nix-shell -p coq_8_13 coqPackages_8_13.serapi
````

and then run sertop, this error is not shown. I have been able to reduce the problem to the presence of the OCAMLPATH in the nix-shell environment, while the contents of OCAMLPATH is absent when installing the package in your user profile using `nix-env -iA nixos.coqPackages.serapi`.

**Comment by Zimmi48** [comment]
Yes, this is expected. We could make it work outside a nix-shell by wrapping the binaries so that they know where to look for their dependencies.

**Comment by dunnl** [comment]
It would be great to have a wrapped binary. I'm trying to use `alectryon-mode` in Emacs on NixOS and I don't know of a simple way to do that except to install Alectryon and friends globally. Is this as simple as calling `wrapProgram` in a hook somewhere?

**Comment by Zimmi48** [comment]
I don't personally have experience with `wrapProgram`, so I'm not sure.

However, if your goal is to *not* install globally, then dropping into an appropriate `nix-shell` should be sufficient, no?

**Comment by dunnl** [comment]
I'm trying to get SerAPI installed globally with Nix (why not?). I wrapped the program with an OCAMLPATH that includes SerAPI's own `site-lib`, but I still get the error message

`sertop: internal error, uncaught exception:
        Fl_package_base.No_such_package("coq-serapi.serlib.firstorder", "")`.

To debug this, I opened a nix shell provided by the existing derivation (as-is, without any wrapping). Inside this shell I manually extended OCAMLPATH to include SerAPI's `/site-lib`. In particular, running `ocamlfind list` shows all of  SerAPI's plugin libraries:

```
$ ocamlfind list
...
coq-serapi          (version: n/a)
coq-serapi.extcoq   (version: 8.16.0+0.16.0)
coq-serapi.serapi_v8_14 (version: 8.16.0+0.16.0)
coq-serapi.serlib   (version: 8.16.0+0.16.0)
coq-serapi.serlib.extraction (version: 8.16.0+0.16.0)
coq-serapi.serlib.firstorder (version: 8.16.0+0.16.0)
coq-serapi.serlib.funind (version: 8.16.0+0.16.0)
coq-serapi.serlib.ltac (version: 8.16.0+0.16.0)
coq-serapi.serlib.ring (version: 8.16.0+0.16.0)
coq-serapi.serlib.ssreflect (version: 8.16.0+0.16.0)
coq-serapi.serlib.ssrmatching (version: 8.16.0+0.16.0)
coq-serapi.sertop_v8_12 (version: 8.16.0+0.16.0)
...
```
However, running `sertop` inside this shell still results in the error above. Why would SerAPI complain about not being able to find a plugin when `ocamlfind` in the same shell clearly finds it?

**Comment by ejgallego** [comment]
Hi @dunnl , indeed, good question.

SerAPI here just relays the error from `ocamlfind` directly. Maybe there is a way to enable some debug code?
