### ISSUE TITLE
Warn when the Coq location is bogus

### ISSUE THREAD

**Issue by Ptival** [ejgallego/coq-serapi#25]
This is minor but when you provide an invalid `coq_location` in `myocamlbuild.ml`, the error message is a bit unclear.

I wonder if there is a way for you to detect and complain that the directory does not exist.

**Comment by ejgallego** [comment]
Indeed, sorry. The `myocamlbuild.ml` file will go entirely away once coq/coq#187 is completed and merged.

**Comment by ejgallego** [comment]
This is solved as now SerAPI builds using ocamlfind.
