### ISSUE TITLE
issue when loading mathcomp/HB

### ISSUE THREAD

**Issue by affeldt-aist** [ejgallego/coq-serapi#260]
Hi,

I am just forwarding an issue identified @Zimmi48 
that I seem to have run into when testing alectryon.
It seems to be an issue that arises by just loading modules as in
```
(Add () "From mathcomp Require Import all_ssreflect.")
(Add () "From HB Require Import structures.")
```

See https://github.com/cpitclaudel/alectryon/issues/71

**Comment by ejgallego** [comment]
Should be fixed upstream by https://github.com/coq/coq/pull/15220

**Comment by ejgallego** [comment]
Closed by https://github.com/ocaml/opam-repository/pull/22087
