### ISSUE TITLE
Support coq 8.14

### ISSUE THREAD

**Issue by SnarkBoojum** [ejgallego/coq-serapi#263]
I wanted to package coq-serapi in Debian, but I already uploaded 8.14 (well, 8.14.0 some time ago and 8.14.1 today), and I see in the opam file that it wants < 8.14.

When will a new version compatible with the latest stable coq be available?

**Comment by palmskog** [comment]
There is already a stable released version for 8.14: https://github.com/ocaml/opam-repository/blob/master/packages/coq-serapi/coq-serapi.8.14.0%2B0.14.0/opam

**Comment by SnarkBoojum** [comment]
Ah, the problem is that 8.13 is still the default branch, so I didn't get to see the newest available version!

**Comment by ejgallego** [comment]
@SnarkBoojum sorry for that, indeed we have quite a big of backlog in the project.
