### ISSUE TITLE
Support for Coq 8.15

### ISSUE THREAD

**Issue by erikmd** [ejgallego/coq-serapi#264]
Dear @ejgallego,
@Zimmi48 told me very recently that the latest release candidate, coq.8.15+rc1 is now in opam-coq-archive:
* https://github.com/coq/opam-coq-archive/pull/1974

Hence this issue to suggest you tag **coq-serapi.8.15+rc1+X.Y.Z** in the upcoming days, similarly to [the process followed with coq.8.14+rc1](https://github.com/ejgallego/coq-serapi/pull/253#issuecomment-924149632).

BTW, don't worry about the opam repos submission: I guess @palmskog might want to take care of the extra-dev PR like the previous time:
* https://github.com/coq/opam-coq-archive/pull/1816

And then I'll release the `coqorg/coq:8.15-rc1` docker-coq images.

Thanks a lot!

**Comment by ejgallego** [comment]
Thanks for opening the issue, will try to release the RC asap.

**Comment by ejgallego** [comment]
#265 open (cc @palmskog ) let's see what CI says

**Comment by ejgallego** [comment]
The commit in #265 is looking good, except for OCaml 4.13 which doesn't have a working ppx_import.

I can tag a RC tomorrow then, however current testing is very basic as unfortunately I didn't have time to add Alectryon to SerAPI's CI yet.

**Comment by Zimmi48** [comment]
Do you know what is the story of ppx_import and OCaml 4.13+?

**Comment by ejgallego** [comment]
> Do you know what is the story of ppx_import and OCaml 4.13+?

ppx_import needs significant work to be ported to the 2.0 ppx stack, fortunately the work has been done by the generous ppx team who volunteered, so modulo testing we should see a ppx_import 2.0 release soon hopefully solving many maintenance problems that arose due to ppx_import "age"

Note that ppx_import is a bit of an special ppx, as it works over the typed tree, as opposed to most ppx which work over the parse tree of OCaml programs.

**Comment by kit-ty-kate** [comment]
> Note that we just pushed a ppx_import release to opam which should solve the compat problems c.f. [ocaml/opam-repository#20444](https://github.com/ocaml/opam-repository/pull/20444)

ppx_import.1.9.0 is now available

**Comment by SnarkBoojum** [comment]
I'm ready to package coq-serapi in Debian whenever you release something I can package. (ppx_import 1.9.0 is in already)

**Comment by ejgallego** [comment]
Thanks, I have a deadline but will get to this quick I hope

**Comment by ejgallego** [comment]
Closed by #265
