### ISSUE TITLE
How does one transform a serapi expression into a normal human readable coq string?

### ISSUE THREAD

**Issue by brando90** [ejgallego/coq-serapi#268]
serapi formatting is machine readable and nice to parse for asts etc but I want to process the ast and get back the string coq would have displayed.

How does one do that?

**Comment by ejgallego** [comment]
You can use `(Print ...)` , or if using `(Query ...)` the `pp_format` option, see the docs.

**Comment by brando90** [comment]
usually the docs are referenced at the top of the readme in a github project -- but I assume these are the one you are referring too http://ejgallego.github.io/coq-serapi/coq-serapi/Serapi/Serapi_protocol/ if not let me know which ones.

Thank you for the help!

**Comment by ejgallego** [comment]
Yes, these are the docs. They are not great TBH, feel free to submit PRs or open issues about them.
