### ISSUE TITLE
No LICENSE info

### ISSUE THREAD

**Issue by Zimmi48** [ejgallego/coq-serapi#27]
Hi Emilio,

Your repository does not currently contain licensing information.
I've had a look at source files which contain copyright information but no licensing information either.
It would be good if you could add a license to your project, especially as other open source projects (such as @Ptival's PeaCoq) depends already on it (and are thus theoretically infringing your copyright).
It will also help for future packaging of SerAPI in Opam, nixpkgs and elsewhere.

Thanks!

PS: I see from jscoq that you must already be pretty well aware of existing licenses since you chose AGPL for it. Since SerAPI is a library, I suggest instead to use one of [MIT](http://choosealicense.com/licenses/mpl-2.0/) (the shortest, simplest), [MPL 2.0](http://choosealicense.com/licenses/mpl-2.0/) (my personal favorite), or [LGPL](http://choosealicense.com/licenses/lgpl-3.0/) (as Coq) but I want to make clear that by these suggestions I am in no way trying to force your choice.

**Comment by ejgallego** [comment]
Hi @Zimmi48 , I will take of this shortly, thanks!
