### ISSUE TITLE
Querying proof term directly with `Query`

### ISSUE THREAD

**Issue by brando90** [ejgallego/coq-serapi#270]
I tried this interaction:
```
(Add () "Lemma addn0 n : 0 + n = n. Proof. intros. simpl.")
(Exec 5)
(Query ((pp ((pp_format PpStr)))) Proof)
```
but I don't get to see the proof term (ideally in human form). Why is that? Am I doing it wrong?

I see:
```
(Answer 3 Ack)
(Answer 3 (ObjList ((CoqString "FIXME UPSTREAM, provide pr_proof"))))
(Answer 3 Completed)
(Query () Proof)
(Answer 4 Ack)
(Answer 4 (ObjList ((CoqProof ((Ser_Evar 8)) () () ()))))
(Answer 4 Completed)
```

but expected something like this:
```
(fun n : nat => ?Goal : 0 + n = n)
```

**Comment by brando90** [comment]
@ejgallego is there a way to extend serapi to do this? I am sort of doing it in a very hacky way were insert a `Show Proof.` statement in my document. Then I receive immediately a feedback response from serapi with the string. Then I get the raw string and give it back to serapi in the parse command to get something like this:
```
(Parse ((ontop 1)) "Definition id := fun x : nat => x.")
(Answer 2 Ack)
(Answer 2
 (ObjList
  ((CoqAst
    ((v
      ((control ()) (attrs ())
       (expr
        (VernacDefinition (NoDischarge Definition)
         (((v (Name (Id id)))
           (loc
            (((fname ToplevelInput) (line_nb 1) (bol_pos 0) (line_nb_last 1)
              (bol_pos_last 0) (bp 11) (ep 13)))))
          ())
         (DefineBody () ()
          ((v
            (CLambdaN
             ((CLocalAssum
               (((v (Name (Id x)))
                 (loc
                  (((fname ToplevelInput) (line_nb 1) (bol_pos 0)
                    (line_nb_last 1) (bol_pos_last 0) (bp 21) (ep 22))))))
               (Default Explicit)
               ((v
                 (CRef
                  ((v (Ser_Qualid (DirPath ()) (Id nat)))
                   (loc
                    (((fname ToplevelInput) (line_nb 1) (bol_pos 0)
                      (line_nb_last 1) (bol_pos_last 0) (bp 25) (ep 28)))))
                  ()))
                (loc
                 (((fname ToplevelInput) (line_nb 1) (bol_pos 0)
                   (line_nb_last 1) (bol_pos_last 0) (bp 25) (ep 28)))))))
             ((v
               (CRef
                ((v (Ser_Qualid (DirPath ()) (Id x)))
                 (loc
                  (((fname ToplevelInput) (line_nb 1) (bol_pos 0)
                    (line_nb_last 1) (bol_pos_last 0) (bp 32) (ep 33)))))
                ()))
              (loc
               (((fname ToplevelInput) (line_nb 1) (bol_pos 0)
                 (line_nb_last 1) (bol_pos_last 0) (bp 32) (ep 33)))))))
           (loc
            (((fname ToplevelInput) (line_nb 1) (bol_pos 0) (line_nb_last 1)
              (bol_pos_last 0) (bp 17) (ep 33)))))
          ())))))
     (loc
      (((fname ToplevelInput) (line_nb 1) (bol_pos 0) (line_nb_last 1)
        (bol_pos_last 0) (bp 0) (ep 34)))))))))
(Answer 2 Completed)
```

but this seems a big hacky. Is it hard to extend serapi with this? It feels it should be easy since serapi doesn't have to modify the CoqAST and can just return it in whatever format it is as long as it's a traversable ast is my guess. What do you think?

**Comment by ejgallego** [comment]
It shouldn't be hard to extend indeed, you can call `Proof.partial_proof` to return the term, which can just then be serialized normally.

I've implemented that in #271, please let me know if that works better for you

**Comment by brando90** [comment]
> It shouldn't be hard to extend indeed, you can call `Proof.partial_proof` to return the term, which can just then be serialized normally.
> 
> I've implemented that in #271, please let me know if that works better for you

I'm not an expert in coq-serapi (but getting better!) but this looks good too me since [`EConstr`](https://coq.github.io/doc/v8.11/api/coq/EConstr/index.html) seems to be the Coq AST constructs I want for processing of the terms. The only confusing point to me is that CoqAST's don't wrap values of that same type but instead wrap vernacs/Vernacexpr.vernac_control (which I assume must include additional syntax like Definitions and other things...).

I will need to make those processed terms back into human strings. I assume the only way to do that is to do:
```
(Print ((pp ((pp_format PpStr)))) (CoqConstr (App (Rel ...) ((Rel ...)))))
```
or something like that. 

Let's merge it so I can opam install the new coq-serapi interface and test it and give feedback! :)

Thanks Emilio.

**Comment by ejgallego** [comment]
I need to find out where my writing about Coq ASTs is, but indeed:
- proofs are represented using "kernel terms"
- documents are represented using "CoqAst" which is a different datatype, coming straight from the parser

There are significant differences between the two.

Yes, you should be able to use `Print` to print a term back, but be sure you pass the `sid` parameter correctly, also for incomplete terms some weird stuff may happen, Coq usually doesn't print proofs often so that part is a bit untested.

Note something about opam, you can use `opam pin add coq-serapi https://github.com/ejgallego/coq-serapi#v8.16+show_proof` to actually have opam install my branch and test locally.

If would be nice if you could test that way and give some feedback before we make a release.

**Comment by brando90** [comment]
> Note something about opam, you can use `opam pin add coq-serapi https://github.com/ejgallego/coq-serapi#v8.16+show_proof` to actually have opam install my branch and test locally.

Btw, I think that didn't work I think (sorry not an opam expert if the solution is easy):
```
brandomiranda~ ❯ opam pin add coq-serapi https://github.com/ejgallego/coq-serapi#v8.16+show_proof
[coq-serapi.8.11.0+0.11.0] fetching sources failed: Unknown archive type: /private/var/folders/_l/ry3nxq4n3753twbdc4dl77800000gn/T/opam-43966-f01c10/coq-serapi
[ERROR] Error getting source from https://github.com/ejgallego/coq-serapi#v8.16+show_proof:
          - Could not extract archive:
            Unknown archive type: /private/var/folders/_l/ry3nxq4n3753twbdc4dl77800000gn/T/opam-43966-f01c10/coq-serapi
```

**Comment by ejgallego** [comment]
That's the correct syntax sorry `opam pin add coq-serapi https://github.com/ejgallego/coq-serapi.git#v8.16+show_proof`

**Comment by brando90** [comment]
hmmm...I think I prefer to use the coq version I have or idk if my project will work...will have to think about it.

**Comment by ejgallego** [comment]
Indeed compat is a problem, but this particular change should be easy to backport to 8.11 ; I'd be happy to take a PR for that branch.
