### ISSUE TITLE
Missing build dependency on mathcomp's ssreflect

### ISSUE THREAD

**Issue by SnarkBoojum** [ejgallego/coq-serapi#283]
While trying to package coq-serapi for Debian, it turns out tests/genarg/move.v wants mathcomp's ssrnat and eqtype.

I guess the opam file needs a dep on coq-mathcomp-ssreflect in addition to what is already declared.

**Comment by ejgallego** [comment]
That's only for the test suite, you can also skip that single test if you want.

**Comment by ejgallego** [comment]
There is a problem adding this to the opam file, tho. `coq-serapi` lives in the main OPAM repos, while `coq-mathcomp-ssreflect` lives in Coq's own private repos, so opam repos' CI will likely fail if I add that.
