### ISSUE TITLE
How to handle "Needs option -impredicative-set."

### ISSUE THREAD

**Issue by dhilst** [ejgallego/coq-serapi#287]
Hello, I'm taking a look in coq-serapi, my use case is to serialize coq files to sexp to be able to inspect these files programmatically without needing to parse the files.

My problem is that the project is compiled with `-impredicative-set` so when I try to run `sercomp` I get this error

```
➜  proj git:(master) ✗ sercomp -Q src,MyProj src/Bar.v                             
Error: File "src/Bar.v", line 1, characters 0-19:
       Needs option -impredicative-set.
```

I created a project to easily replicate this at: https://github.com/dhilst/myproj, to reproduce the problem, clone the repository, run make, and then the above command. If it's something that I can help I'm willing to, it may  be a good way of getting started with coq internals structures 

Regards

**Comment by ejgallego** [comment]
Hi @dhilst , indeed we don't have support for that option yet, fortunately it should be very easy to handle. Can you do a PR?

See how `allow_sprop` is handled in `sertop_init`, the code should mirror that one.

**Comment by dhilst** [comment]
Yes, I take a look into the code on the weekend

**Comment by dhilst** [comment]
Thank you @ejgallego, I will work on the backport of this to the 8.14 branch
