### ISSUE TITLE
Unbound module Feedback

### ISSUE THREAD

**Issue by zjhmale** [ejgallego/coq-serapi#29]
Hi @ejgallego, I just followed the `build` instruction on readme, and everything worked fine until I got to the final step. When I run `make`, it will produce `Unbound module Feedback` building error. At first, I use OCaml 4.04, so I assume maybe it is a version confliction, but when I downgrade to 4.02.3 as you suggested on readme, this error was still standing there, here is the error log.

![image](https://cloud.githubusercontent.com/assets/6234553/21338918/61732e52-c6b5-11e6-9d94-8b0ca4ef6332.png)

**Comment by Ptival** [comment]
Hi @zjhmale , in my experience, this happened when I was building againt the wrong version of Coq.

In particular coq-serapi uses very recently-integrated Coq features. You might want to target 8.6 or trunk rather than 8.5 or less.

**Comment by zjhmale** [comment]
@Ptival Thanks! I download the latest released Coq8.6 from [here](https://coq.inria.fr/download), so maybe it is not caused by version mismatch? But I built the source using OCaml 4.04, maybe I should rebuild it with OCaml 4.02.3 and see what I can get then :)

**Comment by zjhmale** [comment]
After build Coq 8.6 with OCaml 4.02.3 and camlp5 6.15, still get the error.

**Comment by zjhmale** [comment]
Ok, finally figure out how to kindly build coq-serapi. Actually, coq-serapi is bundled with Coq8.6RC1, not Coq8.6 which is currently released. And also should make sure that use exactly the same camlp5 to build Coq source and coq-serapi source.

![image](https://cloud.githubusercontent.com/assets/6234553/21351700/eabe2cbe-c6f8-11e6-987a-9310502c6002.png)

**Comment by ejgallego** [comment]
Hey @zjhmale , actually Coq v8.6rc1 and v8.6 are actually the same , so it is weird you found problems.

Usually, this problem is because you are not pointing to the proper location where Coq is installed.

**Comment by zjhmale** [comment]
@ejgallego Thanks, I can build serapi with Coq8.6 now. With some retrospection, I think a possible reason which caused this build error is that I used to install camlp5 using homebrew not opam, so I also add camlp5 dependency to the build instruction.

**Comment by ejgallego** [comment]
You are right, Camlp5 is not there as it is usually a Coq build-time dependency, we should update a bit the build instructions, I'll try to do ASAP.

**Comment by zjhmale** [comment]
Great! 😄 
>You are right, Camlp5 is not there as it is usually a Coq build-time dependency, we should update a bit the build instructions, I'll try to do ASAP.
