### ISSUE TITLE
Pass arguments from _CoqProject file to coqtop

### ISSUE THREAD

**Issue by psteckler** [ejgallego/coq-serapi#35]
Many Coq codebases use _CoqProject files so that an IDE can pass needed flags to coqtop. It would be nice if sertop could make use of the same resource.

One way to do this would be via a command-line flag, say, "-project-location". The Emacs interface should be able to query the user when sertop starts to be able to pass that to sertop (it could be an option whether to make that query or not).

I believe that PG just reads _CoqProject and inlines its contents to pass to coqtop directly.

**Comment by ejgallego** [comment]
Thanks for reporting, what are the important options, paths? In this regard I plan to reuse the jsCoq package format.

I think I will add a _CoqProject parser to serapi for now, but I need to think for a couple of days.

**Comment by psteckler** [comment]
For my use case, the flags to map physical directories to logical paths is important.

**Comment by ejgallego** [comment]
@psteckler unfortunately I won't have time this week to work on this and #19.

However, SerAPI already supports the `(LibAdd ($L1 ... $Ln) $path $has_ml)`, so you should be able to add load paths using:
```
(LibAdd (UniCoq) "/home/unicoq/" false)
```
as a substitute of `Add LoadPath`, but I admit it is a bit painful.

**Comment by ejgallego** [comment]
By the way SerAPI master is the right branch to use these days after EConstr.

**Comment by psteckler** [comment]
Can I just put Add LoadPath in my script, then, and not bother with command-line arguments to do the mapping? Is there any reason I can't pass Add LoadPath to SerAPI's Add?

**Comment by ejgallego** [comment]
No reason at all, that should work and I use it all the time indeed.

**Comment by psteckler** [comment]
Great, I'll try that.

**Comment by psteckler** [comment]
> By the way SerAPI master is the right branch to use these days after EConstr.

Which branch of your Coq repo does that go with? Is it still `stm+parsing_api`, or do I now use `trunk`?

**Comment by ejgallego** [comment]
The current combination is SerAPI trunk + Coq trunk. I hope it will stay that way for a while.

**Comment by psteckler** [comment]
Good, that's easy to remember. :-)

**Comment by ejgallego** [comment]
:D I guess I'll add a note to the README stating that for the development version `.travis.yml` should give you the information in the most reliable way.

**Comment by psteckler** [comment]
I just looked at the `.travis.yml` file.

It looks like I can just use `trunk` from the main Coq repo, rather than your fork, for SerAPI.

**Comment by ejgallego** [comment]
Indeed, sorry if I was not able to explain that properly. It is also highly recommended you update your findlib.conf so you can find the correct coq packages automatically for merlin.

**Comment by ejgallego** [comment]
I don't plan to support `_CoqProject` anymore; likely further support will come from querying Dune-enabled Coq packages, meanwhile users will have to extract `-R / -Q` from `_CoqProject`.
