### ISSUE TITLE
Add OPAM file

### ISSUE THREAD

**Issue by corwin-of-amber** [ejgallego/coq-serapi#36]
I tried to build the newest version of SerAPI today after not having touched it for some time. The instructions state that I should install ```opam install ocamlfind ocamlbuild ppx_import cmdliner core_kernel sexplib ppx_sexp_conv camlp5```, which I did and worked gloriously but installed sexplib version 133.33 by default. This version seems to be missing a key method ```Conv.Exn_converter.add```. Installing ```sexplib>=114.0``` solved the issue.

I do not know if there is an analogue of ```package.json``` in OPAM, but this at least can be added to the docs.

**Comment by ejgallego** [comment]
Indeed we should ship an `opam` file, and put SerAPI in opam, thanks for the feedback.

What ocaml version are you using?

**Comment by ejgallego** [comment]
[Note to self `core_kernel` is not needed anymore (hopefully we can depend on it for the future)]

**Comment by corwin-of-amber** [comment]
I installed OCaml 4.04.1 since the instructions require 4.04. I used MacPorts to install it (not OPAM).

**Comment by ejgallego** [comment]
Thanks for the info.

**Comment by ejgallego** [comment]
Since the end of the year SerAPI is in OPAM.
