### ISSUE TITLE
Build broken by recent change in Coq master

### ISSUE THREAD

**Issue by tchajed** [ejgallego/coq-serapi#37]
The build now fails with

```
File "serlib/plugins/ltac/ser_tacexpr.ml", line 79, characters 0-262:
Error: This variant or record definition does not match that of type
         'a Tacexpr.core_destruction_arg
       The types for field ElimOnIdent are not equal.
```

The commit that breaks the build is https://github.com/coq/coq/commit/fc218c26c (and notably not the earlier commit that reorganizes `API/API.ml`).

**Comment by ejgallego** [comment]
Indeed, I am aware of it; a solution is on the way.

**Comment by ejgallego** [comment]
By the way, I will provide a `v8.7` branch soon that should be quite stable; adding SerAPI to Coq's Travis is planned, however due to some changes we have been discussing I don't that will happen until late 8.8 / 8.9~alpha starts.

**Comment by ejgallego** [comment]
`master` branch will work again with 8.8+alpha once https://github.com/coq/coq/pull/6570 is merged.
