### ISSUE TITLE
Missing conversion functions for types for the extraction plugin?

### ISSUE THREAD

**Issue by toku-sa-n** [ejgallego/coq-serapi#371]
Hi. While I was viewing serlib's document, I noticed that functions for converting between types for the extraction plugin (e.g., [lang](https://coq.inria.fr/doc/V8.18+rc1/api/coq-core/Extraction_plugin/Table/index.html#type-lang)) and SExp were missing.

Is it okay to send a PR to implement them?

**Comment by ejgallego** [comment]
Hi @toku-sa-n !

Absolutely, a PR to fix this problem would be much welcome! I'd recomment you also add a test to the test suite.

Unfortunately we cannot do this automatically yet, see #82 for a discussion

**Comment by toku-sa-n** [comment]
I may be missing something, but it seems that we need to modify the upstream Coq code to implement the functions because there are neither `wit_*` functions defined in [Extraction_plugin](https://coq.inria.fr/doc/V8.18.0/api/coq-core/Extraction_plugin/index.html) nor types of [`'a Genarg.genarg_type`](https://coq.inria.fr/doc/V8.18.0/api/coq-core/Genarg/index.html#type-genarg_type) defined there. The [G_extraction](https://coq.inria.fr/doc/V8.18.0/api/coq-core/Extraction_plugin/G_extraction/index.html) module where I think such functions are to be defined is empty.

Is it correct?

**Comment by ejgallego** [comment]
This is because the `extraction.mli` file was added. Because of that, it is now not possible to access the AST of extraction commands.

cc @SkySkimmer (coq/coq@99eae36202cef321745355976a257e8332f0b82e)
