### ISSUE TITLE
Can't run `make test` due to an error related to `eqType`

### ISSUE THREAD

**Issue by toku-sa-n** [ejgallego/coq-serapi#373]
Hi. I'm trying to run test suites by `make test`, but I'm getting an error related to `eqType`.

```
%make test -j
dune build --root . --only-packages=coq-serapi @install
dune runtest --root .                    
File "tests/genarg/dune", line 110, characters 0-89:
110 | (rule
111 |  (alias runtest)
112 |  (deps (:input move.v))
113 |  (action (run ./test_roundtrip %{input})))
Error: File "move.v", line 21, characters 28-29
       In environment
       class_of : Type -> Type
       T : Type
       The term "T" has type "Type" while it is expected to have type
        "eqType".
make: *** [Makefile:32: test] エラー 1 
```

I ran `make test` just after cloning and getting into the directory. I also tried uninstalling and reinstalling Coq and `coq-mathcomp-ssreflect`, but didn't work.

I'm on `tags/8.18.0+0.18.1`, and the versions of packages are as follows.

```
%coqc --version
The Coq Proof Assistant, version 8.18.0
compiled with OCaml 4.14.1
```

```
%opam install coq-mathcomp-ssreflect
[NOTE] Package coq-mathcomp-ssreflect is already installed (current version is 2.1.0).
```

How to resolve this error?

Thanks.

(BTW, is asking questions on the GitHub issue OK? I'm posting here because some other questions are asked here, too while Zulip's SerAPI channel didn't seem to be active.)

**Comment by ejgallego** [comment]
@toku-sa-n tests need `coq-mathcomp-ssreflect < 2.0`

**Comment by ejgallego** [comment]
> (BTW, is asking questions on the GitHub issue OK? I'm posting here because some other questions are asked here, too while Zulip's SerAPI channel didn't seem to be active.)

Whatever is easier for you! I am active in Zulip too.

**Comment by toku-sa-n** [comment]
Running `opam install 'coq-mathcomp-ssreflect<2'` and tests passed! Thanks for the solution!
Also, thanks for answering the question about the place to ask too!

**Comment by ejgallego** [comment]
I'm glad the solution was easy, thanks for your patiente.

I'd be great to port the tests to math-comp 2.

As noted in the OPAM file, we cannot properly declare this test dependency because `coq-mathcomp` package doesn't live in the core opam repository, thus CI wouldn't pass :(
