### ISSUE TITLE
Run tests with MC 2

### ISSUE THREAD

**Issue by SnarkBoojum** [ejgallego/coq-serapi#395]
While working on my packaging for coq-serapi in Debian, I hit closed issue #373: it is in fact still a current.

I'm disabling the only failing test file for now.

**Comment by ejgallego** [comment]
Unfortunately math-comp 2 is a lot more heavier to install, so this is not trivial to solve without some effort.

**Comment by ejgallego** [comment]
It should be possible to rewrite the test so we don't need math-comp but just stuff in `Coq.ssreflect` , in fact we want to test the stuff in the Coq plugin.

**Comment by ejgallego** [comment]
Fixed by #399
