### ISSUE TITLE
Spurious completion message when exiting

### ISSUE THREAD

**Issue by cpitclaudel** [ejgallego/coq-serapi#4]
Pressing C-d to exit yields an extra message:

```
$ /build/coq-serapi/sertop.native
# Press C-d here
```

```lisp
(Answer""Ack)
(Answer""Completed)
```

**Comment by ejgallego** [comment]
C-d is translated to a `(Control Quit)` command. Is that a problem? If so will fix immediately.

**Comment by cpitclaudel** [comment]
Ooh shiny. I see. Thanks for explaining; no need to fix :)
