### ISSUE TITLE
[PATCH] Compilation with yojson >= 2.2

### ISSUE THREAD

**Issue by SnarkBoojum** [ejgallego/coq-serapi#420]
Compiling coq-serapi with yojson >= 2.2 means running `find serlib -type f |xargs sed -i -e "s/Result.result/Result.t/g"` ; I just fixed the issue in Debian.

**Comment by ejgallego** [comment]
Hi @SnarkBoojum , I think this is fixed in `master`, sorry for the trouble.

**Comment by ejgallego** [comment]
Will close the issue when we release the 0.20 version, so we can check.

**Comment by ejgallego** [comment]
By the way, the problem here is not due to yojson, but to ppx_deriving dropping the dependency on result.

So the right fix is to have serapi now depend on the `result` OCaml package directly. Before we dependeded on it explicitly.

**Comment by ejgallego** [comment]
This should have been fixed in 0.20.0 , please re-open if some more problems arise.
