### ISSUE TITLE
Documents on error handling in SerAPI?

### ISSUE THREAD

**Issue by jimyu94** [ejgallego/coq-serapi#44]
Could you explain how SerAPI handles errors, and the types of its error messages? Thanks!

**Comment by ejgallego** [comment]
As of today, SerAPI will just relay any exception produced by Coq, wrapper in the `CoqExn` constructor. So from that point of view, you are the same if if calling Coq in the ML API.

Basically, if you get an exception == something went wrong, you want to cancel that span.
