### ISSUE TITLE
Why is `-I` not exposed by sertop?

### ISSUE THREAD

**Issue by Ptival** [ejgallego/coq-serapi#53]
Hey Emilio,

I'm trying to resurrect PeaCoq's code base, and am puzzled by how to replace the old `LibAdd`.

I can seem to get my plugin to start loading, by having `-Q /path/to/plugin,PluginName`, but unfortunately, my `plugin.ml4` opens a file in the same directory, that is compiled as a .cmxs, and Coq fails to know how to load it by default.

But, using CoqIDE, I can add `-I /path/to/plugin`, and then everything works well.

**Comment by ejgallego** [comment]
Oh, that's looks like a bug. Will have a look next week. You can meanwhile hack the -Q handling in serapi to make it work, it should be straightforward.

Coq will hopefully move to an ocamlfind model soon and these kind of issues should hopefully work a bit better.
