### ISSUE TITLE
Error When Adding a Vernac Command

### ISSUE THREAD

**Issue by yangky11** [ejgallego/coq-serapi#56]
Hello,

I have an "Unable to locate library Cring" error when executing `(Add () "Require Export Cring.")` in sertop. But it's OK to run this command in Coq IDE, or in sertop using the full name (`(Add () "Require Export Coq.setoid_ring.Cring.")`). 
Any idea? Thanks.

The full error message. Coq version 8.8.0
```
(Answer 0 Ack)
(Feedback
 ((doc_id 0) (span_id 2) (route 0) (contents (ProcessingIn master))))
(Feedback ((doc_id 0) (span_id 1) (route 0) (contents Processed)))
(Feedback
 ((doc_id 0) (span_id 2) (route 0)
  (contents
   (Message Error
    (((fname ToplevelInput) (line_nb 1) (bol_pos 0) (line_nb_last 1)
      (bol_pos_last 0) (bp 15) (ep 20)))
    (Pp_box (Pp_hovbox 0)
     (Pp_glue
      ((Pp_string Unable) (Pp_print_break 1 0) (Pp_string to)
       (Pp_print_break 1 0) (Pp_string locate) (Pp_print_break 1 0)
       (Pp_string library) (Pp_print_break 1 0) (Pp_string Cring.))))))))
(Answer 0
 (CoqExn
  (((fname ToplevelInput) (line_nb 1) (bol_pos 0) (line_nb_last 1)
    (bol_pos_last 0) (bp 15) (ep 20)))
  ((1 2)) (Backtrace ())
  (CErrors.UserError (locate_library "Unable to locate library Cring."))))
(Answer 0 Completed)
```

**Comment by cpitclaudel** [comment]
@ejgallego , can you clarify why flag is deprecated?

**Comment by ejgallego** [comment]
Oh indeed at the time the idea was to disallow the implicit loading of libraries, when I introduced the flag (2016) I marked it as deprecated; however experience has shown this is a bad idea and we should make implicit to be the default as the same it is on Coq.

SerAPI should move back to non-default implicit then when Coq does.
