### ISSUE TITLE
`make sercomp` fails on my system

### ISSUE THREAD

**Issue by Ptival** [ejgallego/coq-serapi#57]
I get the following message:
```
+ ocamlfind ocamldep -package cmdliner -package coq.intf,coq.stm,sexplib -modules sertop/sercomp.ml > sertop/sercomp.ml.depends
ocamlfind: Package `cmdliner' not found
```

I can solve it by adding `:$(OCAMLPATH)` to the `sercomp:` target in the Makefile, like it is in the other targets. Any reason why it wasn't there? Any reason not to include it?

**Comment by ejgallego** [comment]
Oh indeed that looks like an embarrassing bug, sorry!
