### ISSUE TITLE
How do I setup OPAM installed sertop.el?

### ISSUE THREAD

**Issue by anton-trunov** [ejgallego/coq-serapi#58]
I gave the instructions in `sertop.el` a try,

```elisp
;;; Open `sertop.el` and run `M-x eval-buffer` followed by `M-x
;;; sertop` to get a sertop REPL in Emacs, with highlighting and
;;; pretty-printing (useful for debugging).
```
but I get the following error message from Emacs:

> Process Sertop exited abnormally with code 127

Since all is governed by OPAM there should be a way this setup works out of the box, right?

`sertop` works from the shell. Also, my installation lacks `sertop.native` which is mentioned by `sertop.el`.

**Comment by anton-trunov** [comment]
I moved `sertop.el` fom `~/.opam/coq.8.8.1/.opam-switch/sources/coq-serapi.8.8.0+0.5.3/` directory to `/Users/antontrunov/.opam/coq.8.8.1/bin` and changed `sertop.native` to `sertop` and it seems to work now.

**Comment by ejgallego** [comment]
I will look how to install emacs packages with OPAM and fix this, thanks!

**Comment by ejgallego** [comment]
Note that you can also use `rlwrap sertop --printer=human` and also `--omit-atts` and `--omit-locs` are useful to figure out stuff.

I am not sure how to properly start the documentation of SerAPI, so suggestions are welcome.

**Comment by anton-trunov** [comment]
> I will look how to install emacs packages with OPAM and fix this, thanks!

Having `sertop.el` on MELPA would be awesome as well! 

> rlwrap sertop --printer=human and also --omit-atts and --omit-locs are useful to figure out stuff.

Thanks for this!

> I am not sure how to properly start the documentation of SerAPI, so suggestions are welcome.

I'm still exploring the docs. It would be great to have a quick tutorial (if it's not already there) on what can be done with SerAPI. Like how to implement a simple utility, e.g. simple statistics like `coqwc` provides.

**Comment by ejgallego** [comment]
> Like how to implement a simple utility, e.g. simple statistics like `coqwc` provides.

Note this is done by `sertop` , and the stats processing are in OCaml. We could also use a python program or a node one.

**Comment by ejgallego** [comment]
See https://github.com/ejgallego/coq-serapi/blob/v8.8/sertop/sercomp.ml#L34

**Comment by anton-trunov** [comment]
Oh, this is cool! Thanks for the pointer.

**Comment by anton-trunov** [comment]
I just ran `coqwc` and `sercomp` on the same file and got slightly different results:

```shell
$ sercomp -R .,fcsl --omit_att --omit_loc finmap/ordtype.v

...
Statistics:
Specs:  92
Proofs: 122
Misc:   50
```

```shell
$ coqwc finmap/ordtype.v
     spec    proof comments
      131      105       12 finmap/ordtype.v
```

**Comment by ejgallego** [comment]
Indeed the heuristics are different; for example `sercomp` doesn't count as specs quite a few constructs. Also, `coqwc` is a very simple lexer so it cannot be so precise sometimes.

I'd say let's adjust sercomp to match whatever you think is the right thing to do.

**Comment by anton-trunov** [comment]
ok, thanks -- I'll try to devote some time to this
