### ISSUE TITLE
Invalid characters when feeding back sexps into Coq

### ISSUE THREAD

**Issue by palmskog** [ejgallego/coq-serapi#64]
I generate sexps from Coq source files using a program similar to `sercomp`, and then feed back the results into Coq via `Sexp.of_string`. Mostly, this works quite well, but for some reason the `auto` tactic (and some other built-in tactics) generates expressions like: `(Id auto_#_#_#_4C69D5ED)`. Then, when I deserialize these expressions to get them into Coq, I get errors along the lines of `"Invalid character '#' in identifier \"auto_#_#_#_4C69D5ED\"."`.

If I change the `auto` tactic call in the Coq source file into `Coq.Init.Notations.auto`, I don't get this error, since the identifier no longer has occurences of `#`. However, this workaround doesn't work when a file uses `auto using ...` and similar.

Am I missing something, or is there a way to avoid generating names with `#` in them?

**Comment by ejgallego** [comment]
Hi @palmskog !

I've also wondered what those `auto_#_#..` are in the past. Could you provide a small example so I can reproduce the issue? It could be due to several factors.

By the way, have you tried escaping the `#` in the expression?

**Comment by palmskog** [comment]
@ejgallego here is the example I'm currently using:
```
Require Import List.
Import ListNotations.

Section dedup.
  Variable A : Type.
  Hypothesis A_eq_dec : forall x y : A, {x = y} + {x <> y}.

  Fixpoint dedup (xs : list A) : list A :=
    match xs with
    | [] => []
    | x :: xs => let tail := dedup xs in
                 if in_dec A_eq_dec x xs then
                   tail
                 else
                   x :: tail
    end.

  Lemma dedup_In : forall (x : A) xs,
      In x xs ->
      In x (dedup xs).
  Proof using.
    induction xs; intros; simpl in *.
    - intuition.
    - case in_dec; intuition; subst; simpl; auto.
  Qed.
End dedup.
```
The third-last line results in the following sexp:
```
(VernacExpr
  ()
  (VernacExtend
    (VernacSolve 0)
    ((GenArg raw (OptArg (ExtraArg ltac_selector)) ())
     (GenArg raw (OptArg (ExtraArg ltac_info))     ())
     (GenArg raw
       (ExtraArg tactic)
       (TacThen
         (TacThen
           (TacThen
             (TacThen
               (TacAtom (
                 ((
                   (fname (InFile Dedup_before.v))
                   (line_nb      24)
                   (bol_pos      537)
                   (line_nb_last 24)
                   (bol_pos_last 537)
                   (bp           543)
                   (ep           554)))
                 (TacCase false (
                   ()
                   (((v (
                       CRef
                       ((v (Ident (Id in_dec)))
                        (loc ((
                          (fname (InFile Dedup_before.v))
                          (line_nb      24)
                          (bol_pos      537)
                          (line_nb_last 24)
                          (bol_pos_last 537)
                          (bp           548)
                          (ep           554)))))
                       ()))
                     (loc ()))
                    NoBindings)))))
               (TacAlias (
                 ((
                   (fname (InFile Dedup_before.v))
                   (line_nb      24)
                   (bol_pos      537)
                   (line_nb_last 24)
                   (bol_pos_last 537)
                   (bp           556)
                   (ep           565)))
                 ((Kername
                    (MPfile (
                      DirPath (
                        (Id Tauto)
                        (Id Init)
                        (Id Coq))))
                    (DirPath ())
                    (Id intuition_3AD8AF16))
                  ()))))
             (TacAlias (
               ((
                 (fname (InFile Dedup_before.v))
                 (line_nb      24)
                 (bol_pos      537)
                 (line_nb_last 24)
                 (bol_pos_last 537)
                 (bp           567)
                 (ep           572)))
               ((Kername
                  (MPfile (
                    DirPath (
                      (Id Notations)
                      (Id Init)
                      (Id Coq))))
                  (DirPath ())
                  (Id subst_4C69D532))
                ()))))
           (TacAtom (
             ((
               (fname (InFile Dedup_before.v))
               (line_nb      24)
               (bol_pos      537)
               (line_nb_last 24)
               (bol_pos_last 537)
               (bp           574)
               (ep           579)))
             (TacReduce
               (Simpl
                 ((rBeta  true)
                  (rMatch true)
                  (rFix   true)
                  (rCofix true)
                  (rZeta  true)
                  (rDelta true)
                  (rConst ()))
                 ())
               ((onhyps (())) (concl_occs AllOccurrences))))))
         (TacAlias (
           ((
             (fname (InFile Dedup_before.v))
             (line_nb      24)
             (bol_pos      537)
             (line_nb_last 24)
             (bol_pos_last 537)
             (bp           581)
             (ep           585)))
           ((Kername
              (MPfile (
                DirPath (
                  (Id Notations)
                  (Id Init)
                  (Id Coq))))
              (DirPath ())
              (Id auto_#_#_#_4C69D5ED))
            ((TacGeneric (GenArg raw (OptArg (ExtraArg int_or_var)) ()))
             (TacGeneric (GenArg raw (ExtraArg auto_using) ()))
             (TacGeneric (GenArg raw (ExtraArg hintbases) (())))))))))
     (GenArg raw (ExtraArg ltac_use_default) false))))
```
I did try some naive escaping, but I'll look more into it.

**Comment by ejgallego** [comment]
Aha, this is the `TacAlias` stuff; @herbelin and @ppedrot can may clue us as to why the identifier is like this.

Meanwhile, does the following patch improve the situation?
```patch
@@ -33,7 +33,7 @@ type t   = [%import: Names.Id.t]
 
 type _t            = Id of string [@@deriving sexp]
 let _t_put  id     = Id (Id.to_string id)
-let _t_get (Id id) = Id.of_string id
+let _t_get (Id id) = Id.of_string_soft id
 
 let t_of_sexp sexp = _t_get (_t_of_sexp sexp)
 let sexp_of_t id   = sexp_of__t (_t_put id)
```

**Comment by palmskog** [comment]
The problem persists, even with that patch.

To give more context, if I change `auto` to `Coq.Init.Notations.auto`, I get the following friendly sub-sexp instead:
```
(TacArg ((((fname (InFile Dedup_before.v))
             (line_nb      24)
             (bol_pos      537)
             (line_nb_last 24)
             (bol_pos_last 537)
             (bp           581)
             (ep           604)))
           (TacCall (
             ((
               (fname (InFile Dedup_before.v))
               (line_nb      24)
               (bol_pos      537)
               (line_nb_last 24)
               (bol_pos_last 537)
               (bp           581)
               (ep           604)))
             (((v (
                 Qualid (
                   Ser_Qualid
                   (DirPath (
                     (Id Notations)
                     (Id Init)
                     (Id Coq)))
                   (Id auto))))
               (loc ((
                 (fname (InFile Dedup_before.v))
                 (line_nb      24)
                 (bol_pos      537)
                 (line_nb_last 24)
                 (bol_pos_last 537)
                 (bp           581)
                 (ep           604)))))
              ())))))
```
```

**Comment by ejgallego** [comment]
@palmskog I think you are observing the nuances of name resolution in LTAC, indeed, that is tricky business, let's wait to see what experts say.

Meanwhile, it would be helpful if you could provide the exact command giving the error, I can reproduce your output, however I am not sure what you are doing to trigger the error.

**Comment by palmskog** [comment]
@ejgallego I put all the code in my `compser` program in a topic branch in my serapi fork: https://github.com/palmskog/coq-serapi/tree/compser

The code that feeds back deserialized sexps line-by-line is [here](https://github.com/palmskog/coq-serapi/blob/afbe2f58686ccb1b9e75d3bd5a2a80fd5bfaf86f/sertop/compser.ml#L52). Note that the branch will generate a `compser.native` executable after running `make`.

To produce the error, I do the following:

0. Start with [this Coq file](https://gist.github.com/palmskog/6ca495b89d5f3bb9fb60b6403eff7544).
1. Use `sercomp` on the Coq file to produce a file with one `VernacExpr` sexp per line:
```
./sercomp.native Dedup_before.v | grep ^\ \( > Dedup_before.sexp
```
2. Use `compser` to feed back sexps into Coq:
```
./compser.native Dedup_before.sexp
```
For convenience, I provide the generated sexp file that triggers the error with `compser` [here](https://gist.github.com/palmskog/8ca87d0c6b9cdabf230c2e98963e9ab2).

I will do some experiments with escaping and see if that helps.

**Comment by ppedrot** [comment]
`TacAlias` uses an ugly trick that is also used in some places elsewhere, namely that it generates slightly invalid identifiers in order to have a namespace (in this case containing unique ids) that is distinct from what the user can write. You can track the instances of this hack by looking for `Id.of_string_soft` in the source code. Ideally we should get rid of their use.

**Comment by ejgallego** [comment]
Thanks @ppedrot for the clarification, indeed it would be great if we could move the hack out of the AST as this makes the lifes of people harder [this is not the first time I heard a question about it by other users].

@palmskog , I have tried your example, thanks. However, with the patch I suggested I see no error. Are you sure you applied it properly?

**Comment by palmskog** [comment]
@ejgallego You are right, I must have done something wrong when I applied the patch before. Now it works.

Thank you!

**Comment by ejgallego** [comment]
Cool, thanks to you for the testing. I will merge the patch and push a new release.
