### ISSUE TITLE
Including modified sercomp and compser programs for testing

### ISSUE THREAD

**Issue by palmskog** [ejgallego/coq-serapi#76]
For testing of SerAPI, we are currently maintaining a "clean" version of `sercomp` that doesn't print any statistics (just the s-expressions). We also have a program called `compser` that takes s-expressions as input and just feeds them to Coq and finally does `Stm.finish`. 

The idea is that `compser`( `sercomp` ( `<large_coq_project>`)) should not return any errors (except when `coqc` does).

With SerAPI developing in such a rapid pace (along with Coq), any chance we could get these quite simple programs to be maintained in the `v8.9` branch? For example, we could modify the SerAPI `sercomp` to only print statistics when a certain flag is passed.

**Comment by ejgallego** [comment]
Of course! Let me comment on the two programs separately:

- `sercomp`: IMHO, `sercomp` should behave a bit like `coqc`, that is to say, it should not print anything by default, just "compile"; thus I suggest indeed that we make it silent by default and add a `--mode=silent`, `--mode=stats` and `--mode=sexp` as to select the output mode. Any variation would work. `sercomp` was born as a hack so indeed it is serverly lacking and needs a deep redesign. IMHO we could even make them different binaries, but the core functionality should be shared.
- `compser`: I think I'd be cool to add it, however this is going to share a lot of functionality with `sertop`, so IMHO we should be careful as not to duplicate code here either.

So feel free to submit a PR for review, or I can try to give it a go.

> The idea is that `compser`( `sercomp` ( `<large_coq_project>`)) should not return any errors (except when `coqc` does).

That'd be very cool, however I am sure we are going to find some minor nuisances here as the Coq AST was not designed for this; but maybe we could make this robust for 8.10 I think.

**Comment by ejgallego** [comment]
Umm, I am not sure I am sure about what `sercomp` should be, maybe it should not execute, but just serialize indeed. I guess we can experiment.

In any case, any improvement on the tool(s) and of course maintaining them both in the repository is extremely welcome.

**Comment by palmskog** [comment]
Sounds good, I'll begin by submitting a PR  soon for a more flexible `sercomp`. We can take it from there.

**Comment by palmskog** [comment]
The latest versions of `sercomp` and `compser` are really great. The only feature we really need is multiple-file "simultaneous" processing, for example:
```shell
$ sercomp.exe -Q .,StructTact --mode=sexp StructTactics.v Assoc.v
$ compser.exe -Q .,StructTact StructTactics.sexp Assoc.sexp
```
Here, `sercomp.exe` would know to create the `.sexp` files with the right name. Note that `Assoc.v` is assumed to have a line
 ```coq
Require Import StructTact.StructTactics.
```
and there would be no file `StructTactics.vo` lying around (our current workaround).

@ejgallego do you see any difficulties here? I've been trying to follow the back-and-forth about upstream and `NewDoc` and so on, but would the above be implementable right now?

**Comment by ejgallego** [comment]
Unfortunately I think that we will have to compile the `.vo` files first for now. Then we can process the files one by one.

I have some plans towards this, let me get back to you by mail.

We could have sercomp creating the `.vo` file, but there are some technical difficulties while the above solution will work out of the box.

**Comment by ejgallego** [comment]
As this involves dependency-handling, we cannot do without processing `coqdep`, so things get complicated. I guess at some point we should just piggyback on the Dune support for Coq and have Dune process the project.

**Comment by palmskog** [comment]
I agree that if one wants to guarantee that the `compser.exe` call succeeds, one must first do file dependency analysis. However, in our application, we assume we already have dependency data and will feed files to `sercomp.exe` in the right order. I don't think this needs to be built into `sercomp.exe`.

Another hack we've considered is to insert the sexprialized versions of `Module filename.` and `End Filename.` before and after feeding a file into `compser.exe` (and modifying `Import`s accordingly). This just needs to work the limited cases we're looking at though...

**Comment by palmskog** [comment]
Yes, having the possibility of `foo.sexp` -> `foo.vo` would also solve our problems. So if that's the solution you recommend we're happy to go with that.

**Comment by ejgallego** [comment]
> Yes, having the possibility of `foo.sexp` -> `foo.vo` would also solve our problems. So if that's the solution you recommend we're happy to go with that.

I think that's indeed the easiest and less risky by far :) Let me cook a patch.

**Comment by ejgallego** [comment]
Ok, here you have #87 . It needs some testing and a couple of tweaks, let me know how it goes and when you are happy with it.

I need to go now and will be offline for test most part of tomorrow, will try to get back to you mail ASAP, bye!

**Comment by palmskog** [comment]
Although there may be room for more tweaks, we feel both `sercomp` and `compser` in the `v8.9` branch now work very well for our purposes. Hence, I'm closing this.
