### ISSUE TITLE
[sercomp] Improve error exit codes and display.

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-serapi#98]
As of now `sercomp` provides little information on the origin of the error; we should improve [and document] both error codes and error output, which is almost non-existent now.

**Comment by palmskog** [comment]
Related: neither `sercomp` nor `compser` has any documentation or examples, e.g., in `README.md`. Arguably they can be described as "`coqc` alternatives" at this point.

**Comment by ejgallego** [comment]
Fixed among others by f94cb40ac787b3c87e52a397afb52bed61717331 

Please reopen if further improvements are needed.
